@extends('front-end.master')
@section('title','Checkout | '.$brandName)
@section('meta_robots','noindex,nofollow')
@section('main_content')
<section class="lt-section lt-checkout">
 <div class="lt-section-heading"><div><span>Secure order</span><h1>Checkout</h1></div></div>
 @if($errors->any())<div class="lt-alert is-error">{{ $errors->first() }}</div>@endif
 <div class="lt-checkout-grid">
  <form class="lt-checkout-form" method="post" action="{{ route('checkout.store') }}">{{ csrf_field() }}
   <h2>Delivery information</h2><div class="lt-form-grid">
    <label>Full name<input name="customer_name" value="{{ old('customer_name', optional(auth()->user())->name) }}" required></label>
    <label>Phone<input name="phone" value="{{ old('phone') }}" required></label>
    <label>Email<input type="email" name="email" value="{{ old('email', optional(auth()->user())->email) }}"></label>
    <label>City / Area<input name="city" value="{{ old('city') }}"></label>
    <label class="is-wide">Delivery zone<select id="delivery-zone" name="delivery_zone_id" required><option value="">Select your delivery zone</option>@foreach($zones as $zone)<option value="{{ $zone->id }}" data-charge="{{ (float)$zone->charge }}" data-free-minimum="{{ (float)$zone->free_delivery_minimum }}" data-estimate="{{ $zone->estimated_time }}" {{ (string)old('delivery_zone_id')===(string)$zone->id?'selected':'' }}>{{ $zone->name }} — ৳{{ number_format($zone->charge) }}{{ $zone->free_delivery_minimum ? ' (free over ৳'.number_format($zone->free_delivery_minimum).')' : '' }}</option>@endforeach</select><small id="delivery-estimate">Choose a zone to see delivery time and charge.</small></label>
    <label class="is-wide">Full address<textarea name="address" required>{{ old('address') }}</textarea></label>
    <label class="is-wide">Order note<textarea name="notes">{{ old('notes') }}</textarea></label>
   </div><h2>Coupon</h2><div class="lt-coupon-entry"><input id="coupon-code" name="coupon_code" value="{{ old('coupon_code') }}" placeholder="Enter coupon code"><button id="apply-coupon" class="lt-secondary-button" type="button">Apply coupon</button></div><small id="coupon-message"></small><h2>Payment</h2>
   @foreach($paymentMethods as $method)<label class="lt-payment"><input class="payment-method-radio" type="radio" name="payment_method_id" value="{{ $method->id }}" data-emi="{{ $method->supports_emi?1:0 }}" {{ (string)old('payment_method_id',$paymentMethods->first()->id)===(string)$method->id?'checked':'' }}> <strong>{{ $method->name }}</strong>@if($method->instructions)<small style="display:block;margin-left:22px">{{ $method->instructions }}</small>@endif</label>@if($method->supports_emi)<div class="emi-plan-group" data-method="{{ $method->id }}" style="display:none;margin:10px 0 18px 22px"><label>Installment plan<select name="emi_plan_id" class="emi-plan-select"><option value="">Select EMI tenure</option>@foreach($method->emiPlans as $plan)<option value="{{ $plan->id }}" data-months="{{ $plan->months }}" data-interest="{{ (float)$plan->interest_rate }}" data-fee="{{ (float)$plan->processing_fee }}" data-minimum="{{ (float)$plan->minimum_order }}" {{ (string)old('emi_plan_id')===(string)$plan->id?'selected':'' }}>{{ $plan->months }} months · {{ number_format($plan->interest_rate,1) }}% interest · minimum ৳{{ number_format($plan->minimum_order) }}</option>@endforeach</select></label><strong class="emi-estimate"></strong></div>@endif @endforeach
   <button class="lt-primary-button" type="submit">Place order</button>
  </form>
  <aside class="lt-order-summary"><h2>Order summary</h2>@foreach($items as $item)<div><span>{{ $item['product']->product_name }} × {{ $item['quantity'] }}</span><strong>৳{{ number_format($item['subtotal']) }}</strong></div>@endforeach<hr><div><span>Subtotal</span><strong>৳{{ number_format($subtotal) }}</strong></div><div id="checkout-discount-row" style="display:none"><span>Coupon discount</span><strong id="checkout-discount">−৳0</strong></div><div><span>Delivery</span><strong id="checkout-delivery">Select zone</strong></div><hr><div class="is-total"><span>Total</span><strong id="checkout-total">৳{{ number_format($subtotal) }}</strong></div><p>Delivery charges are calculated automatically from your selected zone.</p></aside>
 </div>
</section>
<script>
(function(){var select=document.getElementById('delivery-zone'),delivery=document.getElementById('checkout-delivery'),total=document.getElementById('checkout-total'),estimate=document.getElementById('delivery-estimate'),subtotal={{ json_encode((float)$subtotal) }},deliveryAmount=0,discountAmount=0;function money(value){return '৳'+Number(value).toLocaleString('en-BD',{maximumFractionDigits:2});}function updateTotal(){total.textContent=money(subtotal-discountAmount+deliveryAmount);}function refresh(){var option=select.options[select.selectedIndex];if(!option||!option.value){deliveryAmount=0;delivery.textContent='Select zone';estimate.textContent='Choose a zone to see delivery time and charge.';updateTotal();return;}deliveryAmount=Number(option.getAttribute('data-charge')||0);var freeMinimum=Number(option.getAttribute('data-free-minimum')||0);if(freeMinimum>0&&subtotal>=freeMinimum)deliveryAmount=0;delivery.textContent=deliveryAmount===0?'Free':money(deliveryAmount);estimate.textContent=option.getAttribute('data-estimate')?'Estimated delivery: '+option.getAttribute('data-estimate'):'Delivery time will be confirmed after ordering.';updateTotal();}select.addEventListener('change',refresh);refresh();document.getElementById('apply-coupon').addEventListener('click',function(){var button=this,code=document.getElementById('coupon-code').value,message=document.getElementById('coupon-message');button.disabled=true;message.textContent='Checking coupon…';fetch('{{ route('checkout.coupon') }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json'},body:JSON.stringify({coupon_code:code})}).then(function(response){return response.json().then(function(data){if(!response.ok)throw data;return data;});}).then(function(data){discountAmount=Number(data.discount);document.getElementById('checkout-discount').textContent='−'+money(discountAmount);document.getElementById('checkout-discount-row').style.display='flex';message.textContent=data.message;updateTotal();}).catch(function(data){discountAmount=0;document.getElementById('checkout-discount-row').style.display='none';message.textContent=data.message||'Unable to apply coupon.';updateTotal();}).then(function(){button.disabled=false;});});}());
</script>
<script>(function(){var radios=document.querySelectorAll('.payment-method-radio'),groups=document.querySelectorAll('.emi-plan-group');function currentTotal(){return Number(document.getElementById('checkout-total').textContent.replace(/[^0-9.]/g,''))||{{ json_encode((float)$subtotal) }};}function estimate(group){var select=group.querySelector('select'),option=select.options[select.selectedIndex],output=group.querySelector('.emi-estimate');if(!option||!option.value){output.textContent='';return;}var total=currentTotal(),minimum=Number(option.dataset.minimum),months=Number(option.dataset.months),interest=Number(option.dataset.interest),fee=Number(option.dataset.fee);output.textContent=total<minimum?'Minimum order is ৳'+minimum.toLocaleString('en-BD'): 'Estimated ৳'+((total+(total*interest/100)+fee)/months).toLocaleString('en-BD',{maximumFractionDigits:2})+' per month';}function refresh(){var selected=document.querySelector('.payment-method-radio:checked');groups.forEach(function(group){var active=selected&&group.dataset.method===selected.value;group.style.display=active?'block':'none';group.querySelector('select').disabled=!active;if(active)estimate(group);});}radios.forEach(function(radio){radio.addEventListener('change',refresh);});groups.forEach(function(group){group.querySelector('select').addEventListener('change',function(){estimate(group);});});new MutationObserver(refresh).observe(document.getElementById('checkout-total'),{childList:true,characterData:true,subtree:true});refresh();}());</script>
@endsection
