@extends('front-end.master')
@section('title','PC Builder | '.$brandName)
@section('meta_description','Build a custom desktop PC with compatible components and live pricing.')
@section('main_content')
<style>.pcb-head{margin:35px 0 20px;padding:30px;border-radius:16px;background:linear-gradient(135deg,#072b47,#126494);color:#fff}.pcb-head h1{margin:4px 0}.pcb-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:22px;margin-bottom:60px}.pcb-list{display:grid;gap:12px}.pcb-group-title{margin:8px 0 -2px;color:#123f61;font-size:18px}.pcb-slot{display:grid;grid-template-columns:54px 180px minmax(0,1fr) auto;align-items:center;gap:15px;padding:17px;border:1px solid #dce5ed;border-radius:12px;background:#fff}.pcb-slot[hidden]{display:none}.pcb-icon{display:grid;place-items:center;width:48px;height:48px;border-radius:10px;background:#eef5fa;color:#0b3d62;font-size:21px}.pcb-label strong,.pcb-selected strong{display:block}.pcb-label small{color:#f5821f}.pcb-selected{display:flex;align-items:center;gap:12px}.pcb-selected img{width:58px;height:48px;object-fit:contain}.pcb-actions{display:flex;gap:7px}.pcb-actions button{padding:9px 12px;border:0;border-radius:6px;cursor:pointer}.pcb-remove{background:#ffebe8;color:#a52c20}.pcb-summary{position:sticky;top:15px;align-self:start;padding:24px;border:1px solid #dce5ed;border-radius:14px;background:#fff;box-shadow:0 10px 30px rgba(11,61,98,.1)}.pcb-summary-tools{display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:12px}.pcb-total{display:flex;justify-content:space-between;margin:20px 0;padding:16px 0;border-block:1px solid #dce5ed;font-size:20px}.pcb-summary button{width:100%;border:0}.pcb-warning{padding:12px;border-radius:7px;background:#fff3dc;color:#875900}.pcb-empty{color:#687986}@media(max-width:850px){.pcb-layout{grid-template-columns:1fr}.pcb-summary{position:static}.pcb-slot{grid-template-columns:48px 1fr}.pcb-choice,.pcb-actions{grid-column:1/-1}}</style>
<section><div class="pcb-head"><span>Choose. Check. Build.</span><h1>Custom PC Builder</h1><p>Select compatible components and see your complete build price instantly.</p></div>
@if(session('success'))<div class="lt-alert is-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="lt-alert is-error">{{ session('error') }}</div>@endif
<div class="pcb-layout"><div class="pcb-list"><h2 class="pcb-group-title">Core Components</h2>
@foreach($slots as $key=>$slot) @if(in_array($key,['processor','cooler','motherboard','ram','storage','graphics','power','casing'],true)) @include('front-end.pages.partials.pc-builder-slot',['key'=>$key,'slot'=>$slot]) @endif @endforeach
<h2 class="pcb-group-title">Peripherals &amp; Others</h2>
@foreach($slots as $key=>$slot) @if(in_array($key,['hdd','monitor'],true)) @include('front-end.pages.partials.pc-builder-slot',['key'=>$key,'slot'=>$slot]) @endif @endforeach
</div>
<aside class="pcb-summary"><div class="pcb-summary-tools"><span>{{ count($build) }} items selected</span><label><input type="checkbox" id="pcb-hide-empty"> Hide unconfigured</label></div><h2>Build summary</h2>@foreach($warnings as $warning)<p class="pcb-warning"><i class="fa fa-exclamation-triangle"></i> {{ $warning }}</p>@endforeach @if(!$warnings)<p><i class="fa fa-check-circle" style="color:#28a55f"></i> No known compatibility conflicts.</p>@endif<div class="pcb-total"><span>Total</span><strong>৳{{ number_format($total) }}</strong></div><form method="post" action="{{ route('pc-builder.cart') }}">{{ csrf_field() }}<button class="lt-primary-button">Add complete build to cart</button></form><p class="pcb-empty"><small>Compatibility checks depend on product attributes configured by the administrator.</small></p></aside></div></section>
<script>document.addEventListener('DOMContentLoaded',function(){var toggle=document.getElementById('pcb-hide-empty');if(toggle)toggle.addEventListener('change',function(){document.querySelectorAll('.pcb-slot[data-configured="0"]').forEach(function(row){row.hidden=toggle.checked;});});});</script>
@auth<section style="margin:-40px 0 60px;padding:24px;border:1px solid #dce5ed;border-radius:14px"><h2>Save this build</h2><form method="post" action="{{ route('saved-builds.store') }}" style="display:flex;gap:10px;flex-wrap:wrap">{{ csrf_field() }}<input name="name" placeholder="Example: Gaming PC July" maxlength="100" required style="flex:1;min-width:220px;padding:11px;border:1px solid #ccd8e0;border-radius:7px"><button class="lt-primary-button" style="border:0">Save to my account</button></form></section>@else<section style="margin:-40px 0 60px"><a class="lt-secondary-button" href="{{ url('/login') }}">Sign in to save this build</a></section>@endauth
<style>.pcb-icon img{width:100%;height:100%;object-fit:contain}</style>
@endsection
