<?php
namespace Tests\Feature;
use App\SiteContactItem;use App\TopAnnouncement;use Illuminate\Support\Facades\Cache;use Illuminate\Support\Facades\DB;use Tests\TestCase;
class TopBarManagementTest extends TestCase {
 private function adminSession(){ $a=DB::table('tbl_admin as a')->join('admin_roles as r','r.id','=','a.role_id')->where('a.is_active',1)->where('r.permissions','like','%"settings"%')->select('a.*')->first();$this->assertNotNull($a);return ['admin_id'=>$a->admin_id,'admin_name'=>$a->admin_name]; }
 public function testEmptyTopBarDoesNotRenderLegacyOrFallbackValues(){DB::beginTransaction();try{TopAnnouncement::query()->delete();SiteContactItem::query()->delete();Cache::forget('site-top-bar');$this->withSession($this->adminSession())->get('/')->assertStatus(200)->assertDontSee('+880 1711-000000')->assertDontSee('lt-topbar-inner');}finally{DB::rollBack();Cache::forget('site-top-bar');}}
 public function testActiveRulesOrderingAndContactLinksRender(){DB::beginTransaction();try{TopAnnouncement::query()->delete();SiteContactItem::query()->delete();TopAnnouncement::create(['message'=>'Lower notice','announcement_type'=>'general','display_location'=>'top_bar','display_mode'=>'ticker','priority'=>1,'display_order'=>0,'is_active'=>1,'show_on_desktop'=>1,'show_on_mobile'=>1]);TopAnnouncement::create(['message'=>'Urgent notice','announcement_type'=>'important','display_location'=>'top_bar','display_mode'=>'ticker','priority'=>4,'display_order'=>5,'is_active'=>1,'show_on_desktop'=>1,'show_on_mobile'=>1]);TopAnnouncement::create(['message'=>'Expired notice','announcement_type'=>'warning','display_location'=>'top_bar','display_mode'=>'ticker','priority'=>4,'display_order'=>0,'expires_at'=>now()->subMinute(),'is_active'=>1,'show_on_desktop'=>1,'show_on_mobile'=>1]);SiteContactItem::create(['contact_type'=>'phone','label'=>'Call Us','value'=>'+880 1711-000000','icon'=>'fa-phone','display_order'=>1,'is_primary'=>1,'is_active'=>1,'show_on_desktop'=>1,'show_on_mobile'=>1]);SiteContactItem::create(['contact_type'=>'email','label'=>'Email','value'=>'public@example.com','icon'=>'fa-envelope','display_order'=>2,'is_active'=>1,'show_on_desktop'=>1,'show_on_mobile'=>0]);Cache::forget('site-top-bar');$response=$this->withSession($this->adminSession())->get('/')->assertStatus(200)->assertSee('Urgent notice')->assertSee('Lower notice')->assertDontSee('Expired notice')->assertSee('tel:+8801711000000')->assertSee('mailto:public@example.com');$this->assertLessThan(strpos($response->getContent(),'Lower notice'),strpos($response->getContent(),'Urgent notice'));}finally{DB::rollBack();Cache::forget('site-top-bar');}}
 public function testAuthorizedAdminCanManageAndUnsafeLinksAreRejected(){DB::beginTransaction();try{$session=$this->adminSession();$payload=['title'=>'','message'=>'Managed notice','announcement_type'=>'offer','show_type_badge'=>1,'display_location'=>'top_bar','display_mode'=>'rotating','link_url'=>'/offers','link_text'=>'View','priority'=>3,'display_order'=>2,'starts_at'=>'','expires_at'=>'','is_active'=>1,'open_in_new_tab'=>0,'show_on_desktop'=>1,'show_on_mobile'=>1];$this->withSession($session)->post(route('admin.announcements.store'),$payload)->assertRedirect('/top-bar-management#announcements');$item=TopAnnouncement::where('message','Managed notice')->firstOrFail();$payload['link_url']='javascript:alert(1)';$this->withSession($session)->patch(route('admin.announcements.update',$item->id),$payload)->assertStatus(422);$contact=['contact_type'=>'whatsapp','label'=>'WhatsApp','value'=>'+880 (1711)-000000','link_url'=>'','icon'=>'fa-whatsapp','default_message'=>'Hello Store','display_order'=>1,'is_primary'=>1,'is_active'=>1,'show_on_desktop'=>1,'show_on_mobile'=>1,'open_in_new_tab'=>1];$this->withSession($session)->post(route('admin.contact-items.store'),$contact)->assertRedirect('/top-bar-management#contacts');$saved=SiteContactItem::where('label','WhatsApp')->firstOrFail();$this->assertSame('https://wa.me/8801711000000?text=Hello%20Store',$saved->resolved_url);$this->withSession($session)->post(route('admin.contact-items.toggle',$saved->id))->assertSessionHas('message');$this->assertFalse((bool)$saved->fresh()->is_active);$this->withSession($session)->delete(route('admin.announcements.destroy',$item->id))->assertSessionHas('message');$this->assertDatabaseMissing('top_announcements',['id'=>$item->id]);}finally{DB::rollBack();Cache::forget('site-top-bar');}}
 public function testTopBarManagerRendersOnItsOwnMenuPage(){ $session=$this->adminSession();$this->withSession($session)->get('/site-customization')->assertStatus(200)->assertDontSee('Top Bar &amp; Customer Contacts');$this->withSession($session)->get('/top-bar-management')->assertStatus(200)->assertSee('Top Bar &amp; Customer Contacts',false)->assertSee('Appearance &amp; behavior',false)->assertSee('Add an announcement')->assertSee('Add a contact action')->assertSee('Top Bar &amp; Contacts',false); }
}
