<?php

return [
    'default_name' => 'Default Product Code',
    'default_template' => '{PREFIX}-{CATEGORY_CODE}-{SUBCATEGORY_CODE}-{BRAND_CODE}-{SERIES_CODE}-{SEQUENCE}',
    'default_separator' => '-',
    'default_sequence_scope' => 'global',
    'default_sequence_length' => 6,
    'default_sequence_start' => 1,
    'default_reset_rule' => 'never',
    'default_auto_generate' => true,
    'default_strict_mode' => true,
    'default_skip_empty_components' => false,
    'default_allow_manual_override' => false,
    'default_allow_regeneration' => true,
    'code_types' => [
        'company' => 'Company Code',
        'category' => 'Category Code',
        'subcategory' => 'Subcategory Code',
        'brand' => 'Brand Code',
        'series' => 'Series Code',
        'product' => 'Product Code',
    ],
    'code_type_defaults' => [
        'company' => [
            'name' => 'Company Code',
            'template' => '{PREFIX}-{NAME_CODE}-{SEQUENCE}',
            'separator' => '-',
            'sequence_scope' => 'global',
            'sequence_length' => 3,
            'sequence_start' => 1,
            'reset_rule' => 'never',
            'strict_mode' => true,
            'skip_empty_components' => false,
            'allow_manual_override' => false,
            'allow_regeneration' => true,
            'components' => [
                ['component_type' => 'prefix', 'position' => 1, 'static_value' => 'CO', 'format_options' => null, 'is_required' => true],
                ['component_type' => 'name_code', 'position' => 2, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'sequence', 'position' => 3, 'static_value' => null, 'format_options' => null, 'is_required' => true],
            ],
        ],
        'category' => [
            'name' => 'Category Code',
            'template' => '{PREFIX}-{NAME_CODE}-{SEQUENCE}',
            'separator' => '-',
            'sequence_scope' => 'global',
            'sequence_length' => 3,
            'sequence_start' => 1,
            'reset_rule' => 'never',
            'strict_mode' => true,
            'skip_empty_components' => false,
            'allow_manual_override' => false,
            'allow_regeneration' => true,
            'components' => [
                ['component_type' => 'prefix', 'position' => 1, 'static_value' => 'CAT', 'format_options' => null, 'is_required' => true],
                ['component_type' => 'name_code', 'position' => 2, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'sequence', 'position' => 3, 'static_value' => null, 'format_options' => null, 'is_required' => true],
            ],
        ],
        'subcategory' => [
            'name' => 'Subcategory Code',
            'template' => '{PREFIX}-{CATEGORY_NAME_CODE}-{NAME_CODE}-{SEQUENCE}',
            'separator' => '-',
            'sequence_scope' => 'category',
            'sequence_length' => 3,
            'sequence_start' => 1,
            'reset_rule' => 'never',
            'strict_mode' => true,
            'skip_empty_components' => false,
            'allow_manual_override' => false,
            'allow_regeneration' => true,
            'components' => [
                ['component_type' => 'prefix', 'position' => 1, 'static_value' => 'SUB', 'format_options' => null, 'is_required' => true],
                ['component_type' => 'category_name_code', 'position' => 2, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'name_code', 'position' => 3, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'sequence', 'position' => 4, 'static_value' => null, 'format_options' => null, 'is_required' => true],
            ],
        ],
        'brand' => [
            'name' => 'Brand Code',
            'template' => '{PREFIX}-{NAME_CODE}-{SEQUENCE}',
            'separator' => '-',
            'sequence_scope' => 'global',
            'sequence_length' => 3,
            'sequence_start' => 1,
            'reset_rule' => 'never',
            'strict_mode' => true,
            'skip_empty_components' => false,
            'allow_manual_override' => false,
            'allow_regeneration' => true,
            'components' => [
                ['component_type' => 'prefix', 'position' => 1, 'static_value' => 'BR', 'format_options' => null, 'is_required' => true],
                ['component_type' => 'name_code', 'position' => 2, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'sequence', 'position' => 3, 'static_value' => null, 'format_options' => null, 'is_required' => true],
            ],
        ],
        'series' => [
            'name' => 'Series Code',
            'template' => '{PREFIX}-{BRAND_NAME_CODE}-{NAME_CODE}-{SEQUENCE}',
            'separator' => '-',
            'sequence_scope' => 'brand',
            'sequence_length' => 3,
            'sequence_start' => 1,
            'reset_rule' => 'never',
            'strict_mode' => true,
            'skip_empty_components' => false,
            'allow_manual_override' => false,
            'allow_regeneration' => true,
            'components' => [
                ['component_type' => 'prefix', 'position' => 1, 'static_value' => 'SER', 'format_options' => null, 'is_required' => true],
                ['component_type' => 'brand_name_code', 'position' => 2, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'name_code', 'position' => 3, 'static_value' => null, 'format_options' => ['length' => 3], 'is_required' => true],
                ['component_type' => 'sequence', 'position' => 4, 'static_value' => null, 'format_options' => null, 'is_required' => true],
            ],
        ],
        'product' => [
            'name' => 'Default Product Code',
            'template' => '{PREFIX}-{CATEGORY_CODE}-{SUBCATEGORY_CODE}-{BRAND_CODE}-{SERIES_CODE}-{SEQUENCE}',
            'separator' => '-',
            'sequence_scope' => 'global',
            'sequence_length' => 6,
            'sequence_start' => 1,
            'reset_rule' => 'never',
            'strict_mode' => true,
            'skip_empty_components' => false,
            'allow_manual_override' => false,
            'allow_regeneration' => true,
            'components' => [
                ['component_type' => 'prefix', 'position' => 1, 'static_value' => 'PRD', 'format_options' => null, 'is_required' => true],
                ['component_type' => 'category_code', 'position' => 2, 'static_value' => null, 'format_options' => null, 'is_required' => true],
                ['component_type' => 'subcategory_code', 'position' => 3, 'static_value' => null, 'format_options' => null, 'is_required' => true],
                ['component_type' => 'brand_code', 'position' => 4, 'static_value' => null, 'format_options' => null, 'is_required' => true],
                ['component_type' => 'series_code', 'position' => 5, 'static_value' => null, 'format_options' => null, 'is_required' => true],
                ['component_type' => 'sequence', 'position' => 6, 'static_value' => null, 'format_options' => null, 'is_required' => true],
            ],
        ],
    ],
    'component_types' => [
        'prefix' => 'Prefix',
        'name_code' => 'Name Code',
        'category_name_code' => 'Category Name Code',
        'subcategory_name_code' => 'Subcategory Name Code',
        'brand_name_code' => 'Brand Name Code',
        'series_name_code' => 'Series Name Code',
        'category_code' => 'Category Code',
        'subcategory_code' => 'Subcategory Code',
        'brand_code' => 'Brand Code',
        'series_code' => 'Series Code',
        'static_text' => 'Static Text',
        'company' => 'Company Code',
        'branch' => 'Branch Code',
        'category' => 'Category Code',
        'subcategory' => 'Subcategory Code',
        'brand' => 'Brand Code',
        'series' => 'Series Code',
        'product_type' => 'Product Type Code',
        'year' => 'Year',
        'year_short' => '2-Digit Year',
        'month' => 'Month',
        'day' => 'Day',
        'date' => 'Full Date',
        'sequence' => 'Numeric Sequence',
        'variant' => 'Variant Code',
        'custom_prefix' => 'Custom Prefix',
        'custom_suffix' => 'Custom Suffix',
        'custom_text' => 'Custom Text',
    ],
    'separators' => [
        '-' => 'Hyphen (-)',
        '/' => 'Slash (/)',
        '.' => 'Dot (.)',
        '_' => 'Underscore (_)',
        '' => 'No separator',
    ],
    'sequence_scopes' => [
        'global' => 'Global',
        'company' => 'Company',
        'branch' => 'Branch',
        'category' => 'Category',
        'subcategory' => 'Subcategory',
        'brand' => 'Brand',
        'series' => 'Series',
    ],
    'reset_rules' => [
        'never' => 'Never reset',
        'yearly' => 'Reset yearly',
        'monthly' => 'Reset monthly',
        'daily' => 'Reset daily',
        'company' => 'Reset by company',
        'branch' => 'Reset by branch',
        'category' => 'Reset by category',
        'subcategory' => 'Reset by subcategory',
        'brand' => 'Reset by brand',
        'series' => 'Reset by series',
    ],
    'product_type_map' => [
        'general' => 'GEN',
        'technology' => 'TECH',
        'clothing' => 'CLO',
        'food' => 'FOOD',
        'medicine' => 'MED',
    ],
];
