<?php

return [
    'default_name' => 'Default Product Code',
    'default_template' => '{CATEGORY}-{BRAND}-{SEQUENCE}',
    'default_separator' => '-',
    'default_sequence_scope' => 'global',
    'default_sequence_length' => 6,
    'default_sequence_start' => 1,
    'default_reset_rule' => 'never',
    'default_auto_generate' => true,
    'default_strict_mode' => true,
    'default_skip_empty_components' => false,
    'default_allow_manual_override' => false,
    'default_allow_regeneration' => true,
    'component_types' => [
        'static_text' => 'Static Text',
        'company' => 'Company Code',
        'branch' => 'Branch Code',
        'category' => 'Category Code',
        'subcategory' => 'Subcategory Code',
        'brand' => 'Brand Code',
        'series' => 'Series Code',
        'product_type' => 'Product Type Code',
        'year' => 'Year',
        'year_short' => '2-Digit Year',
        'month' => 'Month',
        'day' => 'Day',
        'date' => 'Full Date',
        'sequence' => 'Numeric Sequence',
        'variant' => 'Variant Code',
        'custom_prefix' => 'Custom Prefix',
        'custom_suffix' => 'Custom Suffix',
    ],
    'separators' => [
        '-' => 'Hyphen (-)',
        '/' => 'Slash (/)',
        '.' => 'Dot (.)',
        '_' => 'Underscore (_)',
        '' => 'No separator',
    ],
    'sequence_scopes' => [
        'global' => 'Global',
        'company' => 'Company',
        'branch' => 'Branch',
        'category' => 'Category',
        'subcategory' => 'Subcategory',
        'brand' => 'Brand',
        'series' => 'Series',
    ],
    'reset_rules' => [
        'never' => 'Never reset',
        'yearly' => 'Reset yearly',
        'monthly' => 'Reset monthly',
        'daily' => 'Reset daily',
        'company' => 'Reset by company',
        'branch' => 'Reset by branch',
        'category' => 'Reset by category',
        'subcategory' => 'Reset by subcategory',
        'brand' => 'Reset by brand',
        'series' => 'Reset by series',
    ],
    'product_type_map' => [
        'general' => 'GEN',
        'technology' => 'TECH',
        'clothing' => 'CLO',
        'food' => 'FOOD',
        'medicine' => 'MED',
    ],
];
