@extends('admin.admin-master')
@section('admin_main_content')
<style>.au-page{max-width:1180px;padding-bottom:50px}.au-box{margin-bottom:18px;padding:20px;background:#fff;border:1px solid #dfe8ed;border-radius:10px}.au-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.au-field label{display:block;font-size:12px;font-weight:700;color:#3c515e}.au-field input,.au-field select{width:100%;box-sizing:border-box;margin-top:5px;padding:9px;border:1px solid #cbd8df;border-radius:6px}.au-check{display:flex;align-items:center;gap:8px;margin-top:24px;font-size:13px;font-weight:700}.au-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.au-btn{display:inline-block;padding:10px 15px;border:0;border-radius:6px;background:#1467a5;color:#fff;font-weight:700;cursor:pointer}.au-btn.warn{background:#c65312}.au-btn.gray{background:#667787}.au-alert{padding:11px 14px;margin-bottom:15px;border-radius:6px;background:#e9f8ee;color:#176b37}.au-error{background:#fff0f0;color:#9d2828}.au-status{padding:15px;border-left:4px solid #1467a5;background:#f4f8fb}.au-status h3{margin:0 0 6px}.au-commits{width:100%;border-collapse:collapse;margin-top:14px}.au-commits th,.au-commits td{padding:8px;text-align:left;border-bottom:1px solid #e7eef2;font-size:12px}.au-muted{color:#71828c;font-size:12px}.au-secret{font-weight:400;color:#71828c}@media(max-width:800px){.au-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.au-grid{grid-template-columns:1fr}}</style>
<div id="content" class="span10 au-page"><ul class="breadcrumb"><li><i class="icon-home"></i> Admin <i class="icon-angle-right"></i></li><li>System <i class="icon-angle-right"></i></li><li>Application Update</li></ul>
@if(session('message'))<div class="au-alert">{{ session('message') }}</div>@endif @if(session('exception'))<div class="au-alert au-error">{{ session('exception') }}</div>@endif
<div class="au-box"><h2>GitHub Repository</h2><p class="au-muted">Optional manual source updates. The application never pushes to GitHub and never runs arbitrary administrator commands.</p>
<form method="post" action="{{ route('admin.application-update.settings') }}">@csrf<div class="au-grid">
<div class="au-field"><label>Repository integration<select name="enabled"><option value="0" {{ !$settings->enabled?'selected':'' }}>Off</option><option value="1" {{ $settings->enabled?'selected':'' }}>On</option></select></label></div>
<div class="au-field"><label>Repository type<select name="repository_type"><option value="public" {{ $settings->repository_type==='public'?'selected':'' }}>Public</option><option value="private" {{ $settings->repository_type==='private'?'selected':'' }}>Private</option></select></label></div>
<div class="au-field"><label>Branch<input name="branch" value="{{ $settings->branch }}" required></label></div>
<div class="au-field" style="grid-column:1/-1"><label>GitHub repository URL<input name="repository_url" value="{{ $settings->repository_url }}" placeholder="https://github.com/company/project.git" required><span class="au-muted">The running checkout must already have this repository configured as the selected remote.</span></label></div>
<div class="au-field"><label>Remote name<input name="remote_name" value="{{ $settings->remote_name }}" required></label></div>
<div class="au-field"><label>Authentication<select name="authentication"><option value="none" {{ $settings->authentication==='none'?'selected':'' }}>None (public)</option><option value="ssh" {{ $settings->authentication==='ssh'?'selected':'' }}>SSH deploy key</option><option value="pat" {{ $settings->authentication==='pat'?'selected':'' }}>Personal access token</option></select></label></div>
<div class="au-field"><label>Replace secret <span class="au-secret">(never displayed)</span><input type="password" name="secret" data-has-secret="{{ $settings->encrypted_secret ? '1' : '0' }}" autocomplete="new-password" placeholder="Leave blank to keep current secret"></label></div>
<div class="au-field"><label>Dependency handling<select name="dependency_mode"><option value="changed" {{ $settings->dependency_mode==='changed'?'selected':'' }}>Automatically when changed</option><option value="always" {{ $settings->dependency_mode==='always'?'selected':'' }}>Always</option><option value="never" {{ $settings->dependency_mode==='never'?'selected':'' }}>Never</option></select></label></div>
<label class="au-check"><input type="hidden" name="run_migrations" value="0"><input type="checkbox" name="run_migrations" value="1" {{ $settings->run_migrations?'checked':'' }}> Run migrations</label><label class="au-check"><input type="hidden" name="clear_cache" value="0"><input type="checkbox" name="clear_cache" value="1" {{ $settings->clear_cache?'checked':'' }}> Clear cache</label><label class="au-check"><input type="hidden" name="health_check" value="0"><input type="checkbox" name="health_check" value="1" {{ $settings->health_check?'checked':'' }}> Health check</label>
</div><div class="au-actions"><button class="au-btn" type="submit">Save Repository Settings</button></div></form></div>
<div class="au-box"><h2>Application Update</h2>@if($error)<div class="au-alert au-error">{{ $error }}</div>@elseif(!$settings->enabled)<div class="au-status"><h3>Integration disabled</h3><p class="au-muted">The storefront and administration continue working normally.</p></div>@elseif($status)<div class="au-status"><h3>{{ $status['status'] }}</h3><p>{{ $status['message'] }}</p><p class="au-muted">Current: <code>{{ substr((string)$status['local'],0,12) }}</code> · Remote: <code>{{ substr((string)$status['remote'],0,12) }}</code> · Branch: {{ $settings->branch }}</p></div>@endif
@if($settings->enabled)<div class="au-actions"><form method="post" action="{{ route('admin.application-update.test') }}">@csrf<button class="au-btn gray">Test Connection</button></form><form method="post" action="{{ route('admin.application-update.check') }}">@csrf<button class="au-btn">Check for Updates</button></form>@if($status && $status['status']==='Update Available')<form method="post" action="{{ route('admin.application-update.deploy') }}" onsubmit="return confirm('Deploy the reviewed fast-forward update now?')">@csrf<button class="au-btn warn">Deploy Update</button></form>@elseif($status && $status['status']==='Local Changes Detected')<form method="post" action="{{ route('admin.application-update.discard-and-deploy') }}" onsubmit="var value=prompt('This discards tracked server edits. Type DISCARD LOCAL CHANGES to continue.');if(value!=='DISCARD LOCAL CHANGES'){alert('Deployment cancelled.');return false;}this.confirmation.value=value;return true;"><input type="hidden" name="confirmation" value="">@csrf<button class="au-btn warn">Discard Local Changes &amp; Deploy</button></form>@endif</div>@endif
@if($status && count($status['commits']))<h3>Available changes ({{ count($status['commits']) }})</h3><table class="au-commits"><thead><tr><th>Commit</th><th>Subject</th><th>Author</th><th>Date</th></tr></thead><tbody>@foreach($status['commits'] as $commit)<tr><td><code>{{ $commit['short'] }}</code></td><td>{{ $commit['subject'] }}</td><td>{{ $commit['author'] }}</td><td>{{ $commit['date'] }}</td></tr>@endforeach</tbody></table>@endif</div>
<div class="au-box"><h2>Deployment History</h2><table class="au-commits"><thead><tr><th>Date</th><th>Branch</th><th>From</th><th>To</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($history as $item)<tr><td>{{ optional($item->created_at)->format('Y-m-d H:i') }}</td><td>{{ $item->branch }}</td><td><code>{{ substr((string)$item->previous_commit,0,12) }}</code></td><td><code>{{ substr((string)($item->deployed_commit ?: $item->target_commit),0,12) }}</code></td><td>{{ strtoupper($item->status) }}</td><td>@if($item->status==='success' && !$item->rollback_of)<form method="post" action="{{ route('admin.application-update.rollback',$item->id) }}" onsubmit="return confirm('Rollback source to the recorded previous commit? Database migrations will not be reversed.')">@csrf<button class="au-btn gray">Rollback source</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="au-muted">No deployments recorded.</td></tr>@endforelse</tbody></table><p class="au-muted">Rollback restores source using the recorded deployment commit. It does not reverse database migrations.</p></div>
</div>
<script>(function(){var form=document.querySelector('.au-box form[action="{{ route('admin.application-update.settings') }}"]');if(!form)return;var type=form.querySelector('[name="repository_type"]'),auth=form.querySelector('[name="authentication"]'),secret=form.querySelector('[name="secret"]');function sync(){var privateRepo=type.value==='private';auth.required=privateRepo;secret.required=privateRepo&&secret.getAttribute('data-has-secret')!=='1';}type.addEventListener('change',sync);sync();}());</script>
@endsection
