@extends('admin.admin-master')
@section('title','Companies, Brands & Series - '.$brandName)
@section('admin_main_content')
<style>
.ch{padding:26px}.ch-hero{background:linear-gradient(135deg,#073b5c,#0f6b8f);color:#fff;border-radius:14px;padding:25px;margin-bottom:20px}.ch-hero h1{margin:0 0 7px;font-size:27px}.ch-hero p{margin:0;opacity:.86}.ch-flow{display:flex;gap:8px;align-items:center;margin-top:18px}.ch-flow span{background:rgba(255,255,255,.13);padding:8px 12px;border-radius:20px}.ch-filter{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto auto;gap:10px;align-items:end;background:#fff;border:1px solid #dce7ed;border-radius:12px;padding:16px;margin-bottom:18px}.ch-filter label{margin:0}.ch-filter input,.ch-filter select{margin:5px 0 0!important}.ch-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.ch-card{background:#fff;border:1px solid #dce7ed;border-radius:12px;overflow:hidden;box-shadow:0 5px 18px rgba(14,56,76,.06)}.ch-head{padding:18px;border-bottom:1px solid #e8eff3}.ch-head h2{font-size:19px;margin:0 0 4px}.ch-head p{margin:0;color:#667985}.ch-body{padding:18px}.ch label{display:block;font-weight:600;margin:0 0 6px}.ch input[type=text],.ch select{width:100%;box-sizing:border-box;height:38px;margin-bottom:10px}.ch-check{font-weight:400!important}.ch-bulk{display:flex;align-items:center;gap:8px;margin:14px 0 6px;padding:9px;background:#f4f8fa;border-radius:8px}.ch-bulk label{margin:0;font-weight:400}.ch-list{margin-top:10px;max-height:520px;overflow:auto}.ch-item{border-top:1px solid #e8eff3;padding:13px 0}.ch-item:first-child{border-top:0}.ch-item-title{display:flex;gap:8px;align-items:center}.ch-item strong,.ch-item small{display:block}.ch-item small{color:#6b7c87;margin:3px 0 9px}.ch details summary{cursor:pointer;color:#08749b;font-weight:600}.ch details form{margin-top:10px}.ch-empty{color:#7b8b94;padding:15px 0}.ch-error{background:#fff3f1;color:#a32d1e;padding:12px;border-radius:8px;margin-bottom:15px}.ch-success{background:#edf9f1;color:#176536;padding:12px;border-radius:8px;margin-bottom:15px}@media(max-width:1050px){.ch-filter{grid-template-columns:1fr 1fr}.ch-grid{grid-template-columns:1fr}.ch-list{max-height:none}}
</style>
<main id="content" class="span10 ch">
    <header class="ch-hero"><h1>Catalog identity hierarchy</h1><p>Organize products with a clear business structure. Existing manufacturer records work as brands.</p><div class="ch-flow"><span>1. Company</span><b>→</b><span>2. Brand</span><b>→</b><span>3. Product series</span><b>→</b><span>4. Product</span></div></header>
    @if(session('message'))<div class="ch-success">{{ session('message') }}</div>@endif
    @if(session('exception'))<div class="ch-error">{{ session('exception') }}</div>@endif
    @if($errors->any())<div class="ch-error">{{ $errors->first() }}</div>@endif

    <form class="ch-filter" method="get" action="{{ route('catalog-hierarchy.index') }}">
        <label>Search<input type="text" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Company, brand, or series"></label>
        <label>Company<select name="company_id"><option value="">All companies</option>@foreach($filterCompanies as $company)<option value="{{ $company->id }}" {{ ($filters['company_id']??null)==$company->id?'selected':'' }}>{{ $company->name }}</option>@endforeach</select></label>
        <label>Brand<select name="brand_id"><option value="">All brands</option>@foreach($filterBrands as $brand)<option value="{{ $brand->manufacturer_id }}" {{ ($filters['brand_id']??null)==$brand->manufacturer_id?'selected':'' }}>{{ $brand->manufacturer_name }}</option>@endforeach</select></label>
        <label>Status<select name="status"><option value="">Any status</option><option value="active" {{ ($filters['status']??'')==='active'?'selected':'' }}>Active / published</option><option value="inactive" {{ ($filters['status']??'')==='inactive'?'selected':'' }}>Inactive / hidden</option></select></label>
        <button class="btn btn-primary" type="submit"><i class="icon-filter"></i> Filter</button><a class="btn" href="{{ route('catalog-hierarchy.index') }}">Reset</a>
    </form>

    <div class="ch-grid">
        <section class="ch-card"><div class="ch-head"><h2>1. Companies</h2><p>Legal owner or manufacturer group.</p></div><div class="ch-body">
            @include('admin.components.data-transfer',['resource'=>'companies'])
            <form method="post" action="{{ route('catalog-companies.store') }}">{{ csrf_field() }}<label for="company-name">Company name</label><input id="company-name" name="name" type="text" maxlength="160" required placeholder="Example: Lenovo Group"><label class="ch-check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="btn btn-primary" type="submit">Add company</button></form>
            <form id="bulk-companies" method="post" action="{{ route('catalog-companies.bulk-delete') }}" onsubmit="return confirm('Delete selected unused companies?')">{{ csrf_field() }}</form>
            <div class="ch-bulk"><label><input type="checkbox" data-select-all="company"> Select visible</label><button class="btn btn-danger btn-mini" form="bulk-companies" type="submit">Delete selected</button></div>
            <div class="ch-list">@forelse($companies as $company)<article class="ch-item"><div class="ch-item-title"><input type="checkbox" name="company_ids[]" value="{{ $company->id }}" form="bulk-companies" data-check-group="company"><strong>{{ $company->name }}</strong></div><small>{{ $company->brands->count() }} brand(s) · {{ $company->is_active?'Active':'Inactive' }}</small><details><summary>Edit company</summary><form method="post" action="{{ route('catalog-companies.update',$company->id) }}">{{ csrf_field() }}{{ method_field('PATCH') }}<input name="name" value="{{ $company->name }}" required><label class="ch-check"><input type="checkbox" name="is_active" value="1" {{ $company->is_active?'checked':'' }}> Active</label><button class="btn btn-info" type="submit">Save</button></form><form method="post" action="{{ route('catalog-companies.destroy',$company->id) }}" onsubmit="return confirm('Delete this empty company?')">{{ csrf_field() }}{{ method_field('DELETE') }}<button class="btn btn-danger" type="submit">Delete</button></form></details></article>@empty<div class="ch-empty">No companies match the filters.</div>@endforelse</div>
        </div></section>

        <section class="ch-card"><div class="ch-head"><h2>2. Brands</h2><p>Customer-facing names assigned to products.</p></div><div class="ch-body">
            @include('admin.components.data-transfer',['resource'=>'manufacturers'])
            <form method="post" action="{{ route('catalog-brands.store') }}">{{ csrf_field() }}<label for="brand-company">Parent company</label><select id="brand-company" name="company_id" required><option value="">Choose company</option>@foreach($filterCompanies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select><label for="brand-name">Brand name</label><input id="brand-name" name="manufacturer_name" type="text" maxlength="160" required placeholder="Example: Lenovo"><label class="ch-check"><input type="checkbox" name="publication_status" value="1" checked> Published</label><button class="btn btn-primary" type="submit">Add brand</button></form>
            <form id="bulk-brands" method="post" action="{{ route('catalog-brands.bulk-delete') }}" onsubmit="return confirm('Delete selected unused brands?')">{{ csrf_field() }}</form>
            <div class="ch-bulk"><label><input type="checkbox" data-select-all="brand"> Select visible</label><button class="btn btn-danger btn-mini" form="bulk-brands" type="submit">Delete selected</button></div>
            <div class="ch-list">@forelse($brands as $brand)<article class="ch-item"><div class="ch-item-title"><input type="checkbox" name="brand_ids[]" value="{{ $brand->manufacturer_id }}" form="bulk-brands" data-check-group="brand"><strong>{{ $brand->manufacturer_name }}</strong></div><small>{{ optional($brand->company)->name ?: 'No company' }} · {{ $brand->publication_status?'Published':'Hidden' }}</small><details><summary>Edit brand</summary><form method="post" action="{{ route('catalog-brands.update',$brand->manufacturer_id) }}">{{ csrf_field() }}{{ method_field('PATCH') }}<select name="company_id" required>@foreach($filterCompanies as $company)<option value="{{ $company->id }}" {{ $brand->company_id==$company->id?'selected':'' }}>{{ $company->name }}</option>@endforeach</select><input name="manufacturer_name" value="{{ $brand->manufacturer_name }}" required><label class="ch-check"><input type="checkbox" name="publication_status" value="1" {{ $brand->publication_status?'checked':'' }}> Published</label><button class="btn btn-info" type="submit">Save</button></form><form method="post" action="{{ route('catalog-brands.destroy',$brand->manufacturer_id) }}" onsubmit="return confirm('Delete this unused brand?')">{{ csrf_field() }}{{ method_field('DELETE') }}<button class="btn btn-danger" type="submit">Delete</button></form></details></article>@empty<div class="ch-empty">No brands match the filters.</div>@endforelse</div>
        </div></section>

        <section class="ch-card"><div class="ch-head"><h2>3. Product series</h2><p>Families such as ThinkPad, ROG, or MacBook.</p></div><div class="ch-body">
            @include('admin.components.data-transfer',['resource'=>'series'])
            <form method="post" action="{{ route('catalog-series.store') }}">{{ csrf_field() }}<label for="series-brand">Brand</label><select id="series-brand" name="manufacturer_id" required><option value="">Choose brand</option>@foreach($filterBrands as $brand)<option value="{{ $brand->manufacturer_id }}">{{ $brand->manufacturer_name }} — {{ optional($brand->company)->name }}</option>@endforeach</select><label for="series-name">Series name</label><input id="series-name" name="name" type="text" maxlength="160" required placeholder="Example: ThinkPad"><label class="ch-check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="btn btn-primary" type="submit">Add series</button></form>
            <form id="bulk-series" method="post" action="{{ route('catalog-series.bulk-delete') }}" onsubmit="return confirm('Delete selected unused series?')">{{ csrf_field() }}</form>
            <div class="ch-bulk"><label><input type="checkbox" data-select-all="series"> Select visible</label><button class="btn btn-danger btn-mini" form="bulk-series" type="submit">Delete selected</button></div>
            <div class="ch-list">@forelse($series as $item)<article class="ch-item"><div class="ch-item-title"><input type="checkbox" name="series_ids[]" value="{{ $item->id }}" form="bulk-series" data-check-group="series"><strong>{{ $item->name }}</strong></div><small>{{ optional($item->brand)->manufacturer_name ?: 'No brand' }} · {{ $item->is_active?'Active':'Inactive' }}</small><details><summary>Edit series</summary><form method="post" action="{{ route('catalog-series.update',$item->id) }}">{{ csrf_field() }}{{ method_field('PATCH') }}<select name="manufacturer_id" required>@foreach($filterBrands as $brand)<option value="{{ $brand->manufacturer_id }}" {{ $item->manufacturer_id==$brand->manufacturer_id?'selected':'' }}>{{ $brand->manufacturer_name }}</option>@endforeach</select><input name="name" value="{{ $item->name }}" required><label class="ch-check"><input type="checkbox" name="is_active" value="1" {{ $item->is_active?'checked':'' }}> Active</label><button class="btn btn-info" type="submit">Save</button></form><form method="post" action="{{ route('catalog-series.destroy',$item->id) }}" onsubmit="return confirm('Delete this unused series?')">{{ csrf_field() }}{{ method_field('DELETE') }}<button class="btn btn-danger" type="submit">Delete</button></form></details></article>@empty<div class="ch-empty">No product series match the filters.</div>@endforelse</div>
        </div></section>
    </div>
</main>
<script>document.addEventListener('DOMContentLoaded',function(){function visual(inputs){if(window.jQuery&&jQuery.uniform&&jQuery.uniform.update)jQuery.uniform.update(inputs);}document.querySelectorAll('[data-select-all]').forEach(function(toggle){var group=toggle.getAttribute('data-select-all'),boxes=document.querySelectorAll('[data-check-group="'+group+'"]');toggle.addEventListener('change',function(){boxes.forEach(function(box){box.checked=toggle.checked;box.indeterminate=false;});toggle.indeterminate=false;visual(boxes);visual(toggle);});boxes.forEach(function(box){box.addEventListener('change',function(){var checked=document.querySelectorAll('[data-check-group="'+group+'"]:checked').length;toggle.checked=boxes.length>0&&checked===boxes.length;toggle.indeterminate=checked>0&&checked<boxes.length;visual(toggle);visual(box);});});});});</script>
@endsection
