@extends('admin.admin-master')
@section('admin_main_content')
<div id="content" class="span10"><ul class="breadcrumb"><li><i class="icon-home"></i> Admin <i class="icon-angle-right"></i></li><li>Coupons &amp; Offers</li></ul>
@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif @if(session('exception'))<div class="alert alert-error">{{ session('exception') }}</div>@endif @if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif
<div class="box"><div class="box-header"><h2><i class="icon-tags"></i> Create coupon</h2></div><div class="box-content"><form class="form-horizontal" method="post" action="{{ url('/coupons') }}">{{ csrf_field() }}
<div class="row-fluid"><div class="span3"><label>Code</label><input class="span12" name="code" placeholder="SUMMER10" required></div><div class="span3"><label>Type</label><select class="span12" name="discount_type"><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></div><div class="span3"><label>Value</label><input class="span12" type="number" min="0.01" step="0.01" name="discount_value" required></div><div class="span3"><label>Minimum order</label><input class="span12" type="number" min="0" step="0.01" name="minimum_order" value="0"></div></div>
<div class="row-fluid"><div class="span3"><label>Maximum discount</label><input class="span12" type="number" min="0" step="0.01" name="maximum_discount"></div><div class="span3"><label>Usage limit</label><input class="span12" type="number" min="1" name="usage_limit"></div><div class="span3"><label>Starts at</label><input class="span12" type="datetime-local" name="starts_at"></div><div class="span3"><label>Expires at</label><input class="span12" type="datetime-local" name="expires_at"></div></div>
<label>Description</label><input class="span8" name="description" placeholder="Internal promotion note"> <label class="checkbox inline"><input type="checkbox" name="is_active" value="1" checked> Active</label> <button class="btn btn-primary">Create coupon</button></form></div></div>
<div class="box"><div class="box-header"><h2>Available coupons</h2></div><div class="box-content"><table class="table table-striped table-bordered"><thead><tr><th>Code</th><th>Offer</th><th>Rules</th><th>Usage</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($coupons as $coupon)<tr><td><strong>{{ $coupon->code }}</strong><br><small>{{ $coupon->description }}</small></td><td>{{ $coupon->discount_type==='percent' ? number_format($coupon->discount_value).'%' : '৳'.number_format($coupon->discount_value) }}@if($coupon->maximum_discount)<br><small>Max ৳{{ number_format($coupon->maximum_discount) }}</small>@endif</td><td>Minimum ৳{{ number_format($coupon->minimum_order) }}<br><small>{{ $coupon->starts_at ?: 'Immediately' }} — {{ $coupon->expires_at ?: 'No expiry' }}</small></td><td>{{ $coupon->used_count }} / {{ $coupon->usage_limit ?: 'Unlimited' }}</td><td><span class="label {{ $coupon->is_active?'label-success':'' }}">{{ $coupon->is_active?'Active':'Inactive' }}</span></td><td><form method="post" action="{{ url('/coupons/'.$coupon->id.'/toggle') }}" style="display:inline">{{ csrf_field() }}<button class="btn btn-mini">Toggle</button></form> <form method="post" action="{{ url('/coupons/'.$coupon->id.'/delete') }}" style="display:inline">{{ csrf_field() }}<button class="btn btn-mini btn-danger" onclick="return confirm('Delete this coupon?')">Delete</button></form></td></tr>@empty<tr><td colspan="6">No coupons created yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
