@extends('admin.admin-master')

@section('admin_main_content')
<style>
.hfc-page{max-width:1240px;padding-bottom:50px}.hfc-hero{padding:22px 25px;margin-bottom:18px;border-radius:12px;background:linear-gradient(125deg,#123e59,#176f91);color:#fff}.hfc-hero h2{margin:0 0 6px;color:#fff}.hfc-hero p{margin:0;opacity:.88}.hfc-card,.hfc-settings{margin-bottom:16px;background:#fff;border:1px solid #dfe8ed;border-radius:12px;box-shadow:0 4px 16px rgba(30,58,76,.06);overflow:hidden}.hfc-card-head,.hfc-settings-head{padding:15px 20px;border-bottom:1px solid #e7eef2}.hfc-card-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.hfc-card-head h3,.hfc-settings h3{margin:0 0 3px;color:#173f56}.hfc-card-head p,.hfc-settings p{margin:0;color:#71828c;font-size:12px}.hfc-body,.hfc-settings-body{padding:18px 20px}.hfc-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px 16px}.hfc-field{display:flex;flex-direction:column;gap:5px}.hfc-field.full{grid-column:1/-1}.hfc-field label,.hfc-check{font-size:12px;font-weight:700;color:#3c515e}.hfc-field input,.hfc-field select,.hfc-field textarea{box-sizing:border-box;width:100%;min-height:36px;border:1px solid #cbd8df;border-radius:7px;padding:7px 9px;background:#fff}.hfc-field textarea{min-height:68px;resize:vertical}.hfc-field small{color:#7a8992;font-size:11px}.hfc-check{display:flex;align-items:center;gap:7px;padding-top:23px}.hfc-check input{width:16px;min-height:16px}.hfc-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:16px}.hfc-btn{border:0;border-radius:7px;padding:10px 18px;background:#1467a5;color:#fff;font-weight:700;cursor:pointer}.hfc-btn-danger{background:#fff0f0;color:#a22b2b}.hfc-alert{padding:10px 12px;margin-bottom:14px;border-radius:7px;background:#e8f8ee;color:#21713e}.hfc-image{max-width:160px;max-height:80px;object-fit:cover;border-radius:6px;border:1px solid #dce6ed}.hfc-type-dependent{display:none}.hfc-list-order{width:75px}.hfc-preview{display:flex;gap:10px;flex-wrap:wrap;padding:10px;background:#f3f7fa;border-radius:8px}.hfc-preview span{padding:7px 10px;border-radius:5px;background:#0b3d62;color:#fff;font-size:12px}.hfc-preview span.is-disabled{opacity:.45;text-decoration:line-through}@media(max-width:900px){.hfc-grid{grid-template-columns:repeat(2,minmax(150px,1fr))}}@media(max-width:600px){.hfc-grid{grid-template-columns:1fr}.hfc-check{padding-top:0}}
.hfc-guide{margin:0 0 16px;padding:14px 18px;border:1px solid #d8e7ef;border-radius:10px;background:#f7fbfd;color:#49616e}.hfc-guide strong{color:#173f56}.hfc-guide-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px 18px;margin-top:10px;font-size:12px}.hfc-guide-grid span{display:block}.hfc-guide-grid b{color:#1467a5}@media(max-width:900px){.hfc-guide-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.hfc-guide-grid{grid-template-columns:1fr}}
</style>
<style>
.hfc-remove-image{display:flex;align-items:center;gap:7px;color:#a22b2b!important;font-size:11px!important;font-weight:700}
.hfc-remove-image input{width:16px!important;min-height:16px!important}
</style>
<div id="content" class="span10 hfc-page">
    <ul class="breadcrumb"><li><i class="icon-home"></i> Admin <i class="icon-angle-right"></i></li><li>Marketing <i class="icon-angle-right"></i></li><li>Homepage Feature Cards</li></ul>
    @if(session('message'))<div class="hfc-alert">{{ session('message') }}</div>@endif
    @if($errors->any())<div class="hfc-alert" style="background:#fff0f0;color:#a22b2b">{{ $errors->first() }}</div>@endif
    <div class="hfc-hero"><h2>Homepage Feature Cards</h2><p>Add reusable text, image, category, product, brand, and special-offer promotions beside the homepage hero banner.</p></div>
    <div class="hfc-guide"><strong>Quick setup journey</strong> — select a card type, fill the fields shown below, choose a link target, then choose how the card should open. For a full-card click, use <b>Clickable Area: Entire Card</b> and enable <b>Open link in new tab</b>.<div class="hfc-guide-grid"><span><b>Text / CTA:</b> title, description, button, link</span><span><b>Image Banner:</b> image, link, click area</span><span><b>Image + Text:</b> image, title, text, link</span><span><b>Category:</b> category, title, image, link</span><span><b>Subcategory:</b> subcategory, title, image, link</span><span><b>Product:</b> product, title, image, link</span><span><b>Brand:</b> brand, title, image, link</span><span><b>Special Offer:</b> offer text, image, link</span><span><b>Custom:</b> custom text, image, URL</span></div></div>
    <form method="post" action="{{ route('admin.homepage-feature-cards.update') }}" enctype="multipart/form-data" id="hfc-form">@csrf
        <div class="hfc-settings"><div class="hfc-settings-head"><h3>Homepage Card Layout</h3><p>These settings control the promotional area, not the main hero banner.</p></div><div class="hfc-settings-body"><div class="hfc-grid">
            <div class="hfc-field"><label>Layout<select name="config[layout]"><option value="STACKED" {{ $config['layout']==='STACKED'?'selected':'' }}>Stacked</option><option value="GRID" {{ $config['layout']==='GRID'?'selected':'' }}>Grid</option><option value="SLIDER" {{ $config['layout']==='SLIDER'?'selected':'' }}>Slider</option></select></label></div>
            <div class="hfc-field"><label>Maximum Visible Cards<select name="config[max_visible_cards]"><option value="1" {{ (string)$config['max_visible_cards']==='1'?'selected':'' }}>1</option><option value="2" {{ (string)$config['max_visible_cards']==='2'?'selected':'' }}>2</option><option value="3" {{ (string)$config['max_visible_cards']==='3'?'selected':'' }}>3</option><option value="4" {{ (string)$config['max_visible_cards']==='4'?'selected':'' }}>4</option><option value="5" {{ (string)$config['max_visible_cards']==='5'?'selected':'' }}>5</option><option value="AUTO" {{ $config['max_visible_cards']==='AUTO'?'selected':'' }}>Auto</option></select></label></div>
            <div class="hfc-field"><label>Card Gap (px)<input type="number" name="config[card_gap]" value="{{ $config['card_gap'] }}" min="0" max="40"></label></div>
            <div class="hfc-field"><label>Slider Interval (seconds)<input type="number" name="config[slider_interval]" value="{{ $config['slider_interval'] }}" min="3" max="30"></label></div>
            <label class="hfc-check"><input type="hidden" name="config[equal_height]" value="0"><input type="checkbox" name="config[equal_height]" value="1" {{ $config['equal_height']?'checked':'' }}> Equal card height</label>
            <label class="hfc-check"><input type="hidden" name="config[slider_autoplay]" value="0"><input type="checkbox" name="config[slider_autoplay]" value="1" {{ $config['slider_autoplay']?'checked':'' }}> Slider autoplay</label>
            <label class="hfc-check"><input type="hidden" name="config[slider_arrows]" value="0"><input type="checkbox" name="config[slider_arrows]" value="1" {{ $config['slider_arrows']?'checked':'' }}> Slider arrows</label>
            <label class="hfc-check"><input type="hidden" name="config[slider_dots]" value="0"><input type="checkbox" name="config[slider_dots]" value="1" {{ $config['slider_dots']?'checked':'' }}> Slider dots</label>
        </div></div></div>
        <div class="hfc-preview" id="hfc-preview">@foreach($cards as $card)<span class="{{ !$card->is_active?'is-disabled':'' }}">{{ $card->name }}</span>@endforeach</div>
        @foreach($cards as $card)
            <div class="hfc-card" data-card data-type="{{ $card->card_type }}"><div class="hfc-card-head"><div><h3>☰ {{ $card->name }}</h3><p>{{ $card->card_type }} · {{ $card->is_active ? 'Active' : 'Disabled' }}</p></div><button type="button" class="hfc-btn hfc-btn-danger" data-delete-card="{{ $card->id }}">Delete</button></div><div class="hfc-body"><div class="hfc-grid">
                <div class="hfc-field"><label>Name<input name="cards[{{ $card->id }}][name]" value="{{ $card->name }}" maxlength="150"></label></div>
                <div class="hfc-field"><label>Card Type<select name="cards[{{ $card->id }}][card_type]" data-card-type><option value="TEXT_CTA" {{ $card->card_type==='TEXT_CTA'?'selected':'' }}>Text / CTA</option><option value="IMAGE" {{ $card->card_type==='IMAGE'?'selected':'' }}>Image Banner</option><option value="IMAGE_TEXT" {{ $card->card_type==='IMAGE_TEXT'?'selected':'' }}>Image + Text</option><option value="CATEGORY" {{ $card->card_type==='CATEGORY'?'selected':'' }}>Category Promotion</option><option value="SUBCATEGORY" {{ $card->card_type==='SUBCATEGORY'?'selected':'' }}>Subcategory Promotion</option><option value="PRODUCT" {{ $card->card_type==='PRODUCT'?'selected':'' }}>Product Promotion</option><option value="BRAND" {{ $card->card_type==='BRAND'?'selected':'' }}>Brand Promotion</option><option value="SPECIAL_OFFER" {{ $card->card_type==='SPECIAL_OFFER'?'selected':'' }}>Special Offer</option><option value="CUSTOM" {{ $card->card_type==='CUSTOM'?'selected':'' }}>Custom</option></select></label></div>
                <div class="hfc-field"><label>Order<input class="hfc-list-order" type="number" name="cards[{{ $card->id }}][sort_order]" value="{{ $card->sort_order }}" min="0" max="999999"></label></div>
                <label class="hfc-check"><input type="hidden" name="cards[{{ $card->id }}][is_active]" value="0"><input type="checkbox" name="cards[{{ $card->id }}][is_active]" value="1" {{ $card->is_active?'checked':'' }}> Show card</label>
                <div class="hfc-field"><label>Kicker<input name="cards[{{ $card->id }}][kicker_text]" value="{{ $card->kicker_text }}" maxlength="150"></label></div>
                <div class="hfc-field"><label>Title<input name="cards[{{ $card->id }}][title]" value="{{ $card->title }}" maxlength="255"></label></div>
                <div class="hfc-field full"><label>Description<textarea name="cards[{{ $card->id }}][description]" maxlength="1000">{{ $card->description }}</textarea></label></div>
                <div class="hfc-field"><label>Button Text<input name="cards[{{ $card->id }}][button_text]" value="{{ $card->button_text }}" maxlength="100"></label></div>
                <div class="hfc-field"><label>Link Type<select name="cards[{{ $card->id }}][link_type]" data-link-type><option value="NONE" {{ $card->link_type==='NONE'?'selected':'' }}>None</option><option value="CUSTOM_URL" {{ $card->link_type==='CUSTOM_URL'?'selected':'' }}>Custom URL</option><option value="CATEGORY" {{ $card->link_type==='CATEGORY'?'selected':'' }}>Category</option><option value="SUBCATEGORY" {{ $card->link_type==='SUBCATEGORY'?'selected':'' }}>Subcategory</option><option value="PRODUCT" {{ $card->link_type==='PRODUCT'?'selected':'' }}>Product</option><option value="BRAND" {{ $card->link_type==='BRAND'?'selected':'' }}>Brand</option><option value="CONTACT_PAGE" {{ $card->link_type==='CONTACT_PAGE'?'selected':'' }}>Contact Page</option><option value="SHOP_PRODUCTS" {{ $card->link_type==='SHOP_PRODUCTS'?'selected':'' }}>Shop / Products</option><option value="ANCHOR" {{ $card->link_type==='ANCHOR'?'selected':'' }}>Anchor</option></select></label></div>
                <div class="hfc-field hfc-type-dependent" data-link="CUSTOM_URL,ANCHOR"><label>URL / Anchor<input name="cards[{{ $card->id }}][custom_url]" value="{{ $card->custom_url }}" maxlength="255"></label></div>
                <div class="hfc-field hfc-type-dependent" data-link="CATEGORY"><label>Category<select name="cards[{{ $card->id }}][category_id]"><option value="">Select category</option>@foreach($categories as $entity)<option value="{{ $entity->category_id }}" {{ (int)$card->category_id===(int)$entity->category_id?'selected':'' }}>{{ $entity->category_name }}</option>@endforeach</select></label></div>
                <div class="hfc-field hfc-type-dependent" data-link="SUBCATEGORY"><label>Subcategory<select name="cards[{{ $card->id }}][sub_category_id]"><option value="">Select subcategory</option>@foreach($subcategories as $entity)<option value="{{ $entity->sub_category_id }}" {{ (int)$card->sub_category_id===(int)$entity->sub_category_id?'selected':'' }}>{{ $entity->sub_category_name }}</option>@endforeach</select></label></div>
                <div class="hfc-field hfc-type-dependent" data-link="PRODUCT"><label>Product<select name="cards[{{ $card->id }}][product_id]"><option value="">Select product</option>@foreach($products as $entity)<option value="{{ $entity->id }}" {{ (int)$card->product_id===(int)$entity->id?'selected':'' }}>{{ $entity->product_name }}</option>@endforeach</select></label></div>
                <div class="hfc-field hfc-type-dependent" data-link="BRAND"><label>Brand<select name="cards[{{ $card->id }}][manufacturer_id]"><option value="">Select brand</option>@foreach($manufacturers as $entity)<option value="{{ $entity->manufacturer_id }}" {{ (int)$card->manufacturer_id===(int)$entity->manufacturer_id?'selected':'' }}>{{ $entity->manufacturer_name }}</option>@endforeach</select></label></div>
                <div class="hfc-field"><label>Image<input type="file" name="card_image[{{ $card->id }}]" accept=".jpg,.jpeg,.png,.webp">@if($card->resolvedImage())<img class="hfc-image" src="{{ asset($card->resolvedImage()) }}" alt="{{ $card->resolvedAlt() }}">@endif</label>@if($card->image_path)<label class="hfc-remove-image"><input type="checkbox" name="cards[{{ $card->id }}][detach_image]" value="1" data-detach-image> Remove from this card only</label><label class="hfc-remove-image"><input type="checkbox" name="cards[{{ $card->id }}][delete_image]" value="1" data-remove-image> Delete image permanently if unused</label><small>Use “Remove from this card only” for shared images. The file is protected automatically when used elsewhere.</small>@endif</div>
                <div class="hfc-field"><label>Image Alt Text<input name="cards[{{ $card->id }}][image_alt]" value="{{ $card->image_alt }}" maxlength="255"></label></div>
                <div class="hfc-field"><label>Color Style<select name="cards[{{ $card->id }}][color_style]"><option value="THEME_PRIMARY" {{ $card->color_style==='THEME_PRIMARY'?'selected':'' }}>Theme Primary</option><option value="THEME_ACCENT" {{ $card->color_style==='THEME_ACCENT'?'selected':'' }}>Theme Accent</option><option value="BLUE" {{ $card->color_style==='BLUE'?'selected':'' }}>Blue</option><option value="ORANGE" {{ $card->color_style==='ORANGE'?'selected':'' }}>Orange</option><option value="DARK" {{ $card->color_style==='DARK'?'selected':'' }}>Dark</option><option value="LIGHT" {{ $card->color_style==='LIGHT'?'selected':'' }}>Light</option><option value="CUSTOM" {{ $card->color_style==='CUSTOM'?'selected':'' }}>Custom</option></select></label></div>
                <div class="hfc-field"><label>Image Fit<select name="cards[{{ $card->id }}][image_fit]"><option value="COVER" {{ $card->image_fit==='COVER'?'selected':'' }}>Cover</option><option value="CONTAIN" {{ $card->image_fit==='CONTAIN'?'selected':'' }}>Contain</option></select></label></div>
                <div class="hfc-field"><label>Image Position<select name="cards[{{ $card->id }}][image_position]"><option value="CENTER" {{ $card->image_position==='CENTER'?'selected':'' }}>Center</option><option value="TOP" {{ $card->image_position==='TOP'?'selected':'' }}>Top</option><option value="BOTTOM" {{ $card->image_position==='BOTTOM'?'selected':'' }}>Bottom</option><option value="LEFT" {{ $card->image_position==='LEFT'?'selected':'' }}>Left</option><option value="RIGHT" {{ $card->image_position==='RIGHT'?'selected':'' }}>Right</option></select></label></div>
                <div class="hfc-field"><label>Text Position<select name="cards[{{ $card->id }}][text_position]"><option value="TOP_LEFT">Top Left</option><option value="TOP_CENTER">Top Center</option><option value="TOP_RIGHT">Top Right</option><option value="CENTER_LEFT" {{ $card->text_position==='CENTER_LEFT'?'selected':'' }}>Center Left</option><option value="CENTER">Center</option><option value="CENTER_RIGHT">Center Right</option><option value="BOTTOM_LEFT">Bottom Left</option><option value="BOTTOM_CENTER">Bottom Center</option><option value="BOTTOM_RIGHT">Bottom Right</option></select></label></div>
                <div class="hfc-field"><label>Overlay<select name="cards[{{ $card->id }}][overlay_style]"><option value="NONE" {{ $card->overlay_style==='NONE'?'selected':'' }}>None</option><option value="LIGHT" {{ $card->overlay_style==='LIGHT'?'selected':'' }}>Light</option><option value="MEDIUM" {{ $card->overlay_style==='MEDIUM'?'selected':'' }}>Medium</option><option value="DARK" {{ $card->overlay_style==='DARK'?'selected':'' }}>Dark</option></select></label></div>
                <div class="hfc-field"><label>Clickable Area<select name="cards[{{ $card->id }}][clickable_area]"><option value="BUTTON_ONLY" {{ $card->clickable_area==='BUTTON_ONLY'?'selected':'' }}>Button Only</option><option value="ENTIRE_CARD" {{ $card->clickable_area==='ENTIRE_CARD'?'selected':'' }}>Entire Card</option><option value="IMAGE_ONLY" {{ $card->clickable_area==='IMAGE_ONLY'?'selected':'' }}>Image Only</option></select></label></div>
                <label class="hfc-check"><input type="hidden" name="cards[{{ $card->id }}][open_in_new_tab]" value="0"><input type="checkbox" name="cards[{{ $card->id }}][open_in_new_tab]" value="1" {{ $card->open_in_new_tab?'checked':'' }}> Open link in new tab</label>
            </div></div></div>
        @endforeach
        <div class="hfc-card"><div class="hfc-card-head"><div><h3>Add Feature Card</h3><p>Create another card without a fixed Card 3/Card 4 limit.</p></div></div><div class="hfc-body"><div class="hfc-grid"><div class="hfc-field"><label>Name<input name="new_card[name]" maxlength="150" placeholder="Gaming Laptop Offer"></label></div><div class="hfc-field"><label>Card Type<select name="new_card[card_type]"><option value="TEXT_CTA">Text / CTA</option><option value="IMAGE">Image Banner</option><option value="IMAGE_TEXT">Image + Text</option><option value="CATEGORY">Category Promotion</option><option value="PRODUCT">Product Promotion</option><option value="BRAND">Brand Promotion</option><option value="SPECIAL_OFFER">Special Offer</option><option value="CUSTOM">Custom</option></select></label></div></div></div></div>
        <div class="hfc-actions"><button class="hfc-btn" type="submit">Save Homepage Feature Cards</button></div>
    </form>
</div>
<script>
(function(){var form=document.getElementById('hfc-form');if(!form)return;function sync(card){var type=card.querySelector('[data-link-type]');if(!type)return;var value=type.value;card.querySelectorAll('[data-link]').forEach(function(field){var allowed=field.getAttribute('data-link').split(',');field.style.display=allowed.indexOf(value)>-1?'flex':'none';});}document.querySelectorAll('[data-card]').forEach(function(card){sync(card);var type=card.querySelector('[data-link-type]');if(type)type.addEventListener('change',function(){sync(card);});});document.querySelectorAll('[data-delete-card]').forEach(function(button){button.addEventListener('click',function(){if(confirm('Delete this feature card?')){var input=document.createElement('input');input.type='hidden';input.name='delete_card';input.value=button.getAttribute('data-delete-card');form.appendChild(input);form.submit();}});});form.querySelectorAll('[data-remove-image]').forEach(function(input){input.addEventListener('change',function(){if(this.checked){var peer=this.closest('.hfc-field').querySelector('[data-detach-image]');if(peer)peer.checked=false;}});});form.querySelectorAll('[data-detach-image]').forEach(function(input){input.addEventListener('change',function(){if(this.checked){var peer=this.closest('.hfc-field').querySelector('[data-remove-image]');if(peer)peer.checked=false;}});});form.addEventListener('submit',function(event){if(Array.prototype.some.call(form.querySelectorAll('[data-remove-image]'),function(input){return input.checked})&&!confirm('Permanently delete the selected uploaded image(s)? This cannot be undone.'))event.preventDefault();});}());
</script>
@endsection
