@extends('admin.admin-master')
@section('admin_main_content')
<link rel="stylesheet" href="{{ asset('css/admin-pagination.css') }}?v={{ filemtime(public_path('css/admin-pagination.css')) }}">
<link rel="stylesheet" href="{{ asset('css/admin-list-filters.css') }}?v={{ filemtime(public_path('css/admin-list-filters.css')) }}">
<div id="content" class="span10"><ul class="breadcrumb"><li><i class="icon-home"></i> Admin <i class="icon-angle-right"></i></li><li>Inventory</li></ul>@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif
<div class="row-fluid"><div class="span4 statbox green"><div class="number">{{ $counts['tracked'] }}</div><div class="title">tracked products</div></div><div class="span4 statbox yellow"><div class="number">{{ $counts['low'] }}</div><div class="title">low stock</div></div><div class="span4 statbox red"><div class="number">{{ $counts['out'] }}</div><div class="title">out of stock</div></div></div>
<div class="box"><div class="box-header"><h2><i class="halflings-icon tasks"></i><span class="break"></span>Stock Control</h2></div><div class="box-content admin-filtered-list"><form class="admin-list-filters" method="get" action="{{ url('/inventory') }}"><label class="admin-filter-search">Search<input type="search" name="search" value="{{ request('search') }}" placeholder="Name, model, SKU, barcode, or ID"></label><label>Stock status<select name="filter"><option value="">All products</option><option value="low" {{ request('filter')==='low'?'selected':'' }}>Low stock (1–5)</option><option value="out" {{ request('filter')==='out'?'selected':'' }}>Out of stock</option><option value="untracked" {{ request('filter')==='untracked'?'selected':'' }}>Not tracked</option></select></label><label>Category<select name="category_id"><option value="">All categories</option>@foreach($filterCategories as $category)<option value="{{ $category->category_id }}" {{ (string)request('category_id')===(string)$category->category_id?'selected':'' }}>{{ $category->category_name }}</option>@endforeach</select></label><label>Manufacturer<select name="manufacturer_id"><option value="">All manufacturers</option>@foreach($filterManufacturers as $manufacturer)<option value="{{ $manufacturer->manufacturer_id }}" {{ (string)request('manufacturer_id')===(string)$manufacturer->manufacturer_id?'selected':'' }}>{{ $manufacturer->manufacturer_name }}</option>@endforeach</select></label><label>Items per page<select name="per_page">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" {{ $products->perPage()===$size?'selected':'' }}>{{ $size }} products</option>@endforeach</select></label><div class="admin-filter-footer"><output class="admin-filter-result" aria-live="polite"><strong>{{ number_format($products->total()) }}</strong> {{ \Illuminate\Support\Str::plural('product', $products->total()) }} found</output><div class="admin-filter-actions"><button class="btn btn-primary" type="submit"><i class="icon-filter icon-white"></i> Apply filters</button><a class="btn" href="{{ url('/inventory') }}">Clear filters</a></div></div></form>
<table class="table table-striped table-bordered"><thead><tr><th>Product</th><th>SKU</th><th>Current state</th><th>Stock control</th></tr></thead><tbody>@forelse($products as $product)<tr><td><strong>{{ $product->product_name }}</strong><br><small>{{ $product->product_model }}</small></td><td>{{ $product->sku ?: '—' }}</td><td>@if($product->stock_tracking)<span class="label {{ $product->stock_quantity>5?'label-success':($product->stock_quantity>0?'label-warning':'label-important') }}">{{ $product->stock_quantity }} available</span>@else<span class="label">Not tracked</span>@endif</td><td><form class="form-inline" method="post" action="{{ url('/inventory/'.$product->id) }}">{{ csrf_field() }}<label class="checkbox"><input type="checkbox" name="stock_tracking" value="1" {{ $product->stock_tracking?'checked':'' }}> Track</label> <input type="number" min="0" name="stock_quantity" value="{{ $product->stock_quantity }}" style="width:75px" aria-label="Stock quantity for {{ $product->product_name }}"><input type="hidden" name="product_condition" value="{{ $product->product_condition }}"><button class="btn btn-mini btn-primary">Save</button></form></td></tr>@empty<tr><td colspan="4" class="muted" style="padding:30px;text-align:center">No inventory products match these filters.</td></tr>@endforelse</tbody></table>@include('admin.components.pagination',['paginator'=>$products,'itemLabel'=>'products'])</div></div></div>
@endsection
