@extends('admin.admin-master')
@section('title','Edit '.$method->publicName().' - '.$brandName)
@section('admin_main_content')
<style>
.pm-edit-page{padding-bottom:50px;color:#263746}.pm-edit-head{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:22px 25px;margin-bottom:16px;border-radius:14px;color:#fff;background:linear-gradient(125deg,#123e59,#176f91)}.pm-edit-head h1{margin:0 0 5px;color:#fff;font-size:24px}.pm-edit-head p{margin:0;color:rgba(255,255,255,.8)}.pm-edit-shell{padding:20px;border:1px solid #dfe8ed;border-radius:12px;background:#fff}.pm-edit-note{padding:12px 14px;margin-bottom:16px;border:1px solid #cfe3ec;border-radius:8px;color:#385b6d;background:#f2f9fc}.pm-form{margin:0}.pm-section{padding-top:18px;margin-top:18px;border-top:1px solid #dfe8ed}.pm-section:first-child{padding-top:0;margin-top:0;border:0}.pm-section h3{margin:0 0 3px;color:#173f56;font-size:15px}.pm-section>p,.pm-help{color:#71828c;font-size:11px}.pm-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px 16px}.pm-field.full{grid-column:1/-1}.pm-field label{display:block;margin-bottom:5px;color:#3c515e;font-size:11px;font-weight:800}.pm-field input,.pm-field select,.pm-field textarea{box-sizing:border-box;width:100%;min-height:39px;margin:0;border:1px solid #cbd8df;border-radius:7px;padding:8px 10px;box-shadow:none}.pm-field textarea{min-height:75px;resize:vertical}.pm-field input:focus,.pm-field select:focus,.pm-field textarea:focus{border-color:#1988ad;box-shadow:0 0 0 3px rgba(25,136,173,.1);outline:0}.pm-checks{display:flex;flex-wrap:wrap;gap:8px;margin:13px 0}.pm-checks label{padding:7px 9px;border:1px solid #dce6eb;border-radius:17px;background:#fff;font-size:11px;font-weight:700}.pm-checks input{margin:0 5px 0 0}.pm-alert{padding:12px 14px;margin:12px 0;border:1px solid #efd28a;border-radius:8px;color:#6f5720;background:#fff7df}@media(max-width:760px){.pm-edit-head{align-items:flex-start;flex-direction:column}.pm-grid{grid-template-columns:1fr}.pm-field.full{grid-column:auto}}
</style>
<div id="content" class="span10 pm-edit-page">
 <ul class="breadcrumb"><li><i class="icon-home"></i> Admin <i class="icon-angle-right"></i></li><li><a href="{{ route('payment-methods.index') }}">Payment Methods</a> <i class="icon-angle-right"></i></li><li>Edit {{ $method->publicName() }}</li></ul>
 @if($errors->any())<div class="alert alert-error"><strong>The method was not saved.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <header class="pm-edit-head"><div><h1>Edit {{ $method->publicName() }}</h1><p>{{ $method->name }} · {{ $method->code }} · Changes apply only to this payment method.</p></div><a class="btn" href="{{ route('payment-methods.index') }}"><i class="icon-arrow-left"></i> Back to Payment Methods</a></header>
 <div class="pm-edit-note"><i class="icon-info-sign"></i> Review the sections below, then use <strong>Save this payment method</strong>. Other payment methods will not be changed.</div>
 <div class="pm-edit-shell">@include('admin.components.payment-method-form',['method'=>$method])</div>
</div>
<script>(function(){var button=document.querySelector('.pm-edit-shell form button.btn-primary');if(button)button.innerHTML='<i class="icon-save"></i> Save this payment method';}());</script>
@endsection
