@extends('admin.admin-master')
@section('admin_main_content')
<div id="content" class="span10"><ul class="breadcrumb"><li><a href="{{ url('/returns') }}">Returns</a> <i class="icon-angle-right"></i></li><li>{{ $return->return_number }}</li></ul>@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif @if(session('exception'))<div class="alert alert-error">{{ session('exception') }}</div>@endif
<div class="row-fluid"><div class="box span7"><div class="box-header"><h2>Returned items</h2></div><div class="box-content"><table class="table table-bordered"><thead><tr><th>Product</th><th>Unit price</th><th>Qty</th><th>Amount</th><th>Inventory</th></tr></thead><tbody>@foreach($items as $item)<tr><td>{{ $item->product_name }}<br><small>{{ $item->sku }}</small></td><td>৳{{ number_format($item->unit_price,2) }}</td><td>{{ $item->quantity }}</td><td>৳{{ number_format($item->amount,2) }}</td><td>{{ $item->inventory_restored_at?'Restored':($item->restock?'Pending':'Do not restock') }}</td></tr>@endforeach</tbody></table><p><strong>Customer reason:</strong> {{ ucwords(str_replace('_',' ',$return->reason)) }}</p><p>{{ $return->details }}</p></div></div>
<div class="box span5"><div class="box-header"><h2>{{ $return->return_number }}</h2></div><div class="box-content"><p><strong>{{ $return->customer_name }}</strong><br>{{ $return->phone }}<br>{{ $return->email }}</p><p>Order: <strong>{{ $return->order_number }}</strong><br>Status: <span class="label">{{ ucfirst($return->status) }}</span><br>Requested: <strong>৳{{ number_format($return->requested_amount,2) }}</strong>@if($return->approved_amount!==null)<br>Approved: <strong>৳{{ number_format($return->approved_amount,2) }}</strong>@endif</p>
@if($return->status==='requested')<form method="post" action="{{ url('/returns/'.$return->id) }}">{{ csrf_field() }}<label>Approved amount</label><input class="span12" type="number" min="0.01" max="{{ $return->requested_amount }}" step="0.01" name="approved_amount" value="{{ $return->requested_amount }}"><label>Admin note</label><textarea class="span12" name="admin_note"></textarea><button class="btn btn-success" name="action" value="approve">Approve</button> <button class="btn btn-danger" name="action" value="reject" onclick="return confirm('Reject this return?')">Reject</button></form>
@elseif($return->status==='approved')<form method="post" action="{{ url('/returns/'.$return->id) }}">{{ csrf_field() }}<p><strong>Inspection and inventory</strong></p>@foreach($items as $item)<label class="checkbox"><input type="checkbox" name="restock[{{ $item->id }}]" value="1" checked> Restock {{ $item->product_name }} ({{ $item->quantity }})</label>@endforeach<label>Receiving note</label><textarea class="span12" name="admin_note"></textarea><button class="btn btn-primary" name="action" value="receive" onclick="return confirm('Mark items received and update inventory?')">Receive return</button></form>
@elseif($return->status==='received')<form method="post" action="{{ url('/returns/'.$return->id) }}">{{ csrf_field() }}<label>Refund method</label><select class="span12" name="refund_method"><option value="original_payment">Original payment method</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="store_credit">Store credit</option></select><label>Transaction reference</label><input class="span12" name="transaction_reference"><label>Refund note</label><textarea class="span12" name="admin_note"></textarea><button class="btn btn-success" name="action" value="refund" onclick="return confirm('Confirm this refund as completed?')">Complete refund</button></form>
@elseif($return->status==='refunded')<div class="alert alert-success"><strong>{{ $refund->refund_number }}</strong><br>৳{{ number_format($refund->amount,2) }} refunded {{ date('M j, Y',strtotime($refund->refunded_at)) }}</div><a class="btn btn-primary" target="_blank" href="{{ route('credit-notes.show',$creditNote->id) }}">Print credit note</a>@else<div class="alert">This return is closed.</div>@endif
@if($return->admin_note)<hr><p><strong>Latest note:</strong><br>{{ $return->admin_note }}</p>@endif</div></div></div></div>
@endsection
