@extends('admin.admin-master')
@section('admin_main_content')
<style>.health-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.health-card{padding:18px;border:1px solid #dfe7ec;border-radius:11px;background:#fff}.health-card i{float:right;font-size:25px;color:#2ca66f}.health-card.is-warning i{color:#e37a24}.health-card h3{margin:0 0 7px;font-size:14px}.health-card p{margin:0;color:#6a7d8b}.health-dot{display:inline-block;width:8px;height:8px;margin-right:6px;border-radius:50%;background:#2ca66f}.is-warning .health-dot{background:#e37a24}@media(max-width:1000px){.health-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.health-grid{grid-template-columns:1fr}}</style>
<div id="content" class="span10">
<ul class="breadcrumb"><li><i class="icon-home"></i> Admin <i class="icon-angle-right"></i></li><li>System Health &amp; Backups</li></ul>
@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif @if(session('exception'))<div class="alert alert-error">{{ session('exception') }}</div>@endif
<div class="page-header"><h1>System Health <small>Live operational checks and recovery protection</small></h1></div>
<div class="health-grid">@foreach(['database'=>['Database','icon-hdd'],'storage'=>['Storage permissions','icon-folder-open'],'php'=>['PHP runtime','icon-code'],'laravel'=>['Laravel framework','icon-cogs'],'disk'=>['Disk capacity','icon-dashboard'],'environment'=>['Environment safety','icon-lock']] as $key=>$info)<div class="health-card {{ $health[$key]['ok']?'':'is-warning' }}"><i class="{{ $info[1] }}"></i><h3><span class="health-dot"></span>{{ $info[0] }}</h3><p>{{ $health[$key]['message'] }}</p></div>@endforeach</div>
<div class="box"><div class="box-header"><h2><i class="icon-list-alt"></i> Database migrations</h2></div><div class="box-content"><p class="{{ $migrations['ok']?'text-success':'text-error' }}">{{ $migrations['message'] }}</p>@if(!$migrations['ok'] && count($migrations['pending']))<p><strong>Pending:</strong> {{ implode(', ', $migrations['pending']) }}</p><form method="post" action="{{ url('/system-health/migrations/run') }}" onsubmit="return confirm('Run all pending database migrations now? Create a database backup first if this is a production system.')">{{ csrf_field() }}<button class="btn btn-danger"><i class="icon-refresh"></i> Run pending migrations</button></form>@endif</div></div>
<div class="row-fluid"><div class="box span7"><div class="box-header"><h2><i class="icon-save"></i> Backups</h2></div><div class="box-content"><p>Choose one of the three backup types. Full backups include both SQL data and uploaded site media.</p>
<form method="post" action="{{ url('/system-health/backup') }}" style="display:inline">{{ csrf_field() }}<button class="btn btn-primary" onclick="this.disabled=true;this.form.submit()"><i class="icon-save"></i> 1. Database backup</button></form>
<form method="post" action="{{ url('/system-health/media-backup') }}" style="display:inline">{{ csrf_field() }}<button class="btn btn-info" onclick="this.disabled=true;this.form.submit()"><i class="icon-picture"></i> 2. Media backup</button></form>
<form method="post" action="{{ url('/system-health/full-backup') }}" style="display:inline">{{ csrf_field() }}<button class="btn btn-success" onclick="this.disabled=true;this.form.submit()"><i class="icon-save"></i> 3. Full backup</button></form>
<hr><h3><i class="icon-upload"></i> 1. Restore database</h3><p>Restore a generated <code>.sql.gz</code> file and replace database data.</p><form method="post" action="{{ url('/system-health/restore') }}" enctype="multipart/form-data" onsubmit="return confirm('This will replace the current database. Continue?')">{{ csrf_field() }}<input type="file" name="backup" accept=".gz,application/gzip" required> <button class="btn btn-warning"><i class="icon-upload"></i> Restore database</button></form>
<hr><h3><i class="icon-picture"></i> 2. Restore media</h3><p>Restore a generated <code>.media.tar.gz</code> file without changing database data.</p><form method="post" action="{{ url('/system-health/media-restore') }}" enctype="multipart/form-data" onsubmit="return confirm('This will overwrite matching uploaded media files. Continue?')">{{ csrf_field() }}<input type="file" name="media_backup" accept=".tar.gz,application/gzip" required> <button class="btn btn-warning"><i class="icon-upload"></i> Restore media</button></form>
<hr><h3><i class="icon-save"></i> 3. Restore full backup</h3><p>Restore a generated <code>.full.tar.gz</code> file, including database and uploaded images.</p><form method="post" action="{{ url('/system-health/full-restore') }}" enctype="multipart/form-data" onsubmit="return confirm('This will replace the current database and uploaded media. Continue?')">{{ csrf_field() }}<input type="file" name="full_backup" accept=".tar.gz,application/gzip" required> <button class="btn btn-warning"><i class="icon-upload"></i> Restore full backup</button></form>
<hr><table class="table table-striped table-bordered"><thead><tr><th>Backup</th><th>Size</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>@forelse($backups as $backup)<tr><td><strong>{{ $backup->filename }}</strong><br><small>By {{ $backup->created_by }}</small></td><td>{{ $backup->size_bytes?number_format($backup->size_bytes/1024,1).' KB':'—' }}</td><td><span class="label {{ $backup->status==='completed'?'label-success':($backup->status==='failed'?'label-important':'') }}">{{ ucfirst($backup->status) }}</span>@if($backup->error)<br><small>{{ $backup->error }}</small>@endif</td><td>{{ date('M j, Y g:i A',strtotime($backup->created_at)) }}</td><td>@if($backup->status==='completed')<a class="btn btn-mini btn-success" href="{{ url('/system-health/backups/'.$backup->id.'/download') }}"><i class="icon-download"></i> Download</a>@endif <form method="post" action="{{ url('/system-health/backups/'.$backup->id.'/delete') }}" style="display:inline">{{ csrf_field() }}<button class="btn btn-mini btn-danger" onclick="return confirm('Permanently delete this backup file?')">Delete</button></form></td></tr>@empty<tr><td colspan="5">No backups exist yet. Create the first backup now.</td></tr>@endforelse</tbody></table></div></div>
<div class="box span5"><div class="box-header"><h2><i class="icon-wrench"></i> Maintenance tools</h2></div><div class="box-content"><h3>Application caches</h3><p>Clear cached configuration, routes, application data, and compiled views after configuration or deployment changes.</p><form method="post" action="{{ url('/system-health/clear-cache') }}">{{ csrf_field() }}<button class="btn btn-warning" onclick="return confirm('Clear all application caches?')"><i class="icon-refresh"></i> Clear caches</button></form><hr><h3>Automatic schedule</h3><p><strong>Daily database backup:</strong> 2:00 AM</p><p><strong>Retention:</strong> 14 days</p><div class="alert alert-info">The server must run <code>php artisan schedule:run</code> every minute for automatic backups. On Windows, configure this in Task Scheduler.</div><hr><h3>Recovery safety</h3><p>Database and full restores create a safety backup first. Media restore only overwrites matching media files.</p></div></div></div></div>
@endsection
