<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ServiceClaimController extends Controller {
 public function form(){return view('front-end.pages.service-request');}
 public function store(Request $request){$this->validate($request,['order_number'=>'required|max:40','phone'=>'required|max:30','customer_name'=>'required|max:120','email'=>'nullable|email|max:150','claim_type'=>'required|in:warranty,repair,return,replacement','product_id'=>'required|integer','serial_number'=>'nullable|max:150','issue_description'=>'required|min:15|max:4000']);$order=DB::table('orders')->where('order_number',strtoupper(trim($request->order_number)))->first();$given=preg_replace('/\D+/','',(string)$request->phone);$stored=$order?preg_replace('/\D+/','',(string)$order->phone):'';if(!$order||!$given||!hash_equals($stored,$given))return redirect()->back()->withInput()->withErrors(['order_number'=>'Order number and phone do not match our records.']);$item=DB::table('order_items')->where('order_id',$order->id)->where('product_id',$request->product_id)->first();if(!$item)return redirect()->back()->withInput()->withErrors(['product_id'=>'That product is not part of this order.']);$number='RMA-'.date('ymd').'-'.strtoupper(str_random(6));$id=DB::table('service_claims')->insertGetId(['claim_number'=>$number,'user_id'=>auth()->id(),'order_id'=>$order->id,'product_id'=>$item->product_id,'customer_name'=>$request->customer_name,'email'=>$request->email,'phone'=>$request->phone,'claim_type'=>$request->claim_type,'product_name'=>$item->product_name,'serial_number'=>$request->serial_number,'issue_description'=>$request->issue_description,'status'=>'submitted','created_at'=>now(),'updated_at'=>now()]);DB::table('store_notifications')->insert(['recipient_type'=>'admin','order_id'=>$order->id,'email'=>$request->email,'title'=>'New service claim '.$number,'message'=>$request->customer_name.' submitted a '.ucfirst($request->claim_type).' request for '.$item->product_name.'.','action_url'=>url('/service-claims/'.$id),'email_status'=>'not_requested','created_at'=>now(),'updated_at'=>now()]);$request->session()->put('service_claim_'.$id,true);return redirect()->route('service-claims.show',$id)->with('success','Your service request was submitted.');}
 public function products(Request $request){$order=DB::table('orders')->where('order_number',strtoupper(trim((string)$request->order_number)))->first();$given=preg_replace('/\D+/','',(string)$request->phone);$stored=$order?preg_replace('/\D+/','',(string)$order->phone):'';if(!$order||!$given||!hash_equals($stored,$given))return response()->json(['message'=>'Order details do not match.'],422);return response()->json(DB::table('order_items')->where('order_id',$order->id)->select('product_id','product_name','sku')->get());}
 public function show(Request $request,$id){$claim=DB::table('service_claims')->where('id',$id)->first();abort_unless($claim,404);$allowed=$request->session()->has('admin_id')||$request->session()->get('service_claim_'.$id)||(auth()->check()&&(int)$claim->user_id===(int)auth()->id());abort_unless($allowed,403);return view('front-end.pages.service-claim-status',compact('claim'));}
}
