<?php
namespace App\Http\Controllers;
use App\Services\TopBarService;use App\SiteContactItem;use App\TopAnnouncement;use Illuminate\Http\Request;use Illuminate\Support\Facades\Cache;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Redirect;use Illuminate\Validation\Rule;
class TopBarAdminController extends Controller {
 public function index(){
  $settings=DB::table('site_settings')->pluck('setting_value','setting_key');
  $topAnnouncements=\Schema::hasTable('top_announcements')?TopAnnouncement::orderByDesc('priority')->orderBy('display_order')->get():collect();
  $siteContactItems=\Schema::hasTable('site_contact_items')?SiteContactItem::orderByDesc('is_primary')->orderBy('display_order')->get():collect();
  return view('admin.admin-pages.top-bar-management',compact('settings','topAnnouncements','siteContactItems'));
 }
 public function updateSettings(Request $r,TopBarService $s){$this->validate($r,['top_bar_enabled'=>'required|boolean','top_bar_mobile_enabled'=>'required|boolean','top_bar_sticky'=>'required|boolean','top_bar_show_announcement'=>'required|boolean','top_bar_show_contacts'=>'required|boolean','top_bar_show_support_link'=>'required|boolean','top_bar_background_color'=>['required','regex:/^#[0-9a-fA-F]{6}$/'],'top_bar_text_color'=>['required','regex:/^#[0-9a-fA-F]{6}$/'],'top_bar_link_color'=>['required','regex:/^#[0-9a-fA-F]{6}$/'],'top_bar_height'=>'required|integer|min:28|max:80','announcement_rotation_interval'=>'required|integer|min:2000|max:30000','support_link_enabled'=>'required|boolean','support_link_label'=>'nullable|string|max:100','support_link_type'=>['required',Rule::in(['contact_page','support_page','email','whatsapp','custom_url'])],'support_link_url'=>'nullable|string|max:500','support_link_open_new_tab'=>'required|boolean','support_link_icon'=>['nullable',Rule::in($this->icons())]]);if($r->boolean('support_link_enabled')&&!$r->filled('support_link_label'))return Redirect::back()->withInput()->withErrors(['support_link_label'=>'A label is required when the support link is enabled.']);if($r->boolean('support_link_enabled')&&$r->support_link_type!=='contact_page'&&!$this->safeSupportValue($r->support_link_type,$r->support_link_url))return Redirect::back()->withInput()->withErrors(['support_link_url'=>'Enter a valid value for the selected support type.']);foreach(array_keys($r->except('_token')) as $key){DB::table('site_settings')->updateOrInsert(['setting_key'=>$key],['setting_value'=>trim(strip_tags((string)$r->input($key))),'created_at'=>now(),'updated_at'=>now()]);}Cache::forget('site-settings');$s->clear();return Redirect::to('/top-bar-management#appearance')->with('message','Top bar settings updated.');}
 public function storeAnnouncement(Request $r,TopBarService $s){$d=$this->announcementData($r);$d['created_by']=session('admin_name');$d['updated_by']=session('admin_name');TopAnnouncement::create($d);$s->clear();return $this->done('Announcement added.','announcements');}
 public function updateAnnouncement(Request $r,$id,TopBarService $s){$d=$this->announcementData($r);$d['updated_by']=session('admin_name');TopAnnouncement::findOrFail($id)->update($d);$s->clear();return $this->done('Announcement updated.','announcements');}
 public function toggleAnnouncement($id,TopBarService $s){$i=TopAnnouncement::findOrFail($id);$i->update(['is_active'=>!$i->is_active,'updated_by'=>session('admin_name')]);$s->clear();return $this->done('Announcement visibility updated.','announcements');}
 public function deleteAnnouncement($id,TopBarService $s){TopAnnouncement::findOrFail($id)->delete();$s->clear();return $this->done('Announcement permanently deleted.','announcements');}
 public function storeContact(Request $r,TopBarService $s){$i=SiteContactItem::create($this->contactData($r));$this->primary($i);$s->clear();return $this->done('Contact item added.','contacts');}
 public function updateContact(Request $r,$id,TopBarService $s){$i=SiteContactItem::findOrFail($id);$i->update($this->contactData($r));$this->primary($i);$s->clear();return $this->done('Contact item updated.','contacts');}
 public function toggleContact($id,TopBarService $s){$i=SiteContactItem::findOrFail($id);$i->update(['is_active'=>!$i->is_active]);$s->clear();return $this->done('Contact visibility updated.','contacts');}
 public function deleteContact($id,TopBarService $s){SiteContactItem::findOrFail($id)->delete();$s->clear();return $this->done('Contact item removed.','contacts');}
 private function announcementData(Request $r){$this->validate($r,['title'=>'nullable|string|max:150','message'=>'required|string|max:500','announcement_type'=>['required',Rule::in(['general','offer','important','warning','delivery','payment','system','custom'])],'show_type_badge'=>'required|boolean','display_location'=>['required',Rule::in(['top_bar','homepage','login_page','top_bar_and_login','all_public_pages'])],'display_mode'=>['required',Rule::in(['static','scrolling','rotating','ticker'])],'link_url'=>'nullable|string|max:500','link_text'=>'nullable|string|max:100','priority'=>'required|integer|min:1|max:4','display_order'=>'nullable|integer|min:0','starts_at'=>'nullable|date','expires_at'=>'nullable|date|after_or_equal:starts_at','is_active'=>'required|boolean','open_in_new_tab'=>'required|boolean','show_on_desktop'=>'required|boolean','show_on_mobile'=>'required|boolean']);if($r->filled('link_url')&&!$this->safeUrl($r->link_url))abort(422,'Use an internal path or HTTPS URL.');return ['title'=>$this->clean($r->title),'message'=>$this->clean($r->message),'announcement_type'=>$r->announcement_type,'show_type_badge'=>$r->boolean('show_type_badge'),'display_location'=>$r->display_location,'display_mode'=>$r->display_mode,'link_url'=>$r->filled('link_url')?trim($r->link_url):null,'link_text'=>$this->clean($r->link_text),'open_in_new_tab'=>$r->boolean('open_in_new_tab'),'priority'=>(int)$r->priority,'display_order'=>(int)$r->input('display_order',0),'starts_at'=>$r->starts_at?:null,'expires_at'=>$r->expires_at?:null,'is_active'=>$r->boolean('is_active'),'show_on_desktop'=>$r->boolean('show_on_desktop'),'show_on_mobile'=>$r->boolean('show_on_mobile')];}
 private function contactData(Request $r){$this->validate($r,['contact_type'=>['required',Rule::in(['phone','mobile','hotline','email','whatsapp','support_page','custom_link'])],'label'=>'required|string|max:100','value'=>'required|string|max:255','link_url'=>'nullable|string|max:500','icon'=>['nullable',Rule::in($this->icons())],'default_message'=>'nullable|string|max:500','display_order'=>'nullable|integer|min:0','is_primary'=>'required|boolean','is_active'=>'required|boolean','show_on_desktop'=>'required|boolean','show_on_mobile'=>'required|boolean','open_in_new_tab'=>'required|boolean']);if($r->contact_type==='email'&&!filter_var($r->value,FILTER_VALIDATE_EMAIL))abort(422,'Enter a valid email.');if(in_array($r->contact_type,['phone','mobile','hotline','whatsapp'],true)&&!preg_match('/^\+?[0-9()\-\s.]{5,50}$/',$r->value))abort(422,'Enter a valid number.');if(in_array($r->contact_type,['support_page','custom_link'],true)&&!$this->safeUrl($r->link_url))abort(422,'Use an internal path or HTTPS URL.');return ['contact_type'=>$r->contact_type,'label'=>$this->clean($r->label),'value'=>$this->clean($r->value),'link_url'=>$r->filled('link_url')?trim($r->link_url):null,'icon'=>$r->icon?:$this->defaultIcon($r->contact_type),'default_message'=>$this->clean($r->default_message),'display_order'=>(int)$r->input('display_order',0),'is_primary'=>$r->boolean('is_primary'),'is_active'=>$r->boolean('is_active'),'show_on_desktop'=>$r->boolean('show_on_desktop'),'show_on_mobile'=>$r->boolean('show_on_mobile'),'open_in_new_tab'=>$r->boolean('open_in_new_tab')];}
 private function primary($i){if($i->is_primary)SiteContactItem::where('contact_type',$i->contact_type)->where('id','<>',$i->id)->update(['is_primary'=>0]);}private function done($m,$tab='appearance'){return Redirect::to('/top-bar-management#'.$tab)->with('message',$m);}private function safeUrl($u){return $u&&((strpos($u,'/')===0&&strpos($u,'//')!==0)||(filter_var($u,FILTER_VALIDATE_URL)&&strtolower(parse_url($u,PHP_URL_SCHEME))==='https'));}private function safeSupportValue($t,$v){if($t==='email')return filter_var($v,FILTER_VALIDATE_EMAIL);if($t==='whatsapp')return preg_match('/^\+?[0-9()\-\s.]{5,50}$/',(string)$v);return $this->safeUrl($v);}private function clean($v){if($v===null)return null;$v=preg_replace('/<(script|iframe|object|embed|style)\b[^>]*>.*?<\/\1>/is','',(string)$v);return trim(strip_tags($v));}private function icons(){return ['fa-phone','fa-mobile','fa-envelope','fa-whatsapp','fa-life-ring','fa-headphones','fa-link','fa-info-circle'];}private function defaultIcon($t){return ['phone'=>'fa-phone','mobile'=>'fa-mobile','hotline'=>'fa-headphones','email'=>'fa-envelope','whatsapp'=>'fa-whatsapp','support_page'=>'fa-life-ring','custom_link'=>'fa-link'][$t];}
}
