@php
    $editingProduct = isset($product_info) ? $product_info : null;
    $profile = old('industry_profile', $editingProduct->industry_profile ?? 'general');
    $variantRows = old('variants', isset($productVariants) ? $productVariants->map(function($row){ return (array)$row; })->all() : []);
    $lotRows = old('lots', isset($productLots) ? $productLots->map(function($row){ return (array)$row; })->all() : []);
@endphp
<style>
.industry-card{margin:16px 0;padding:16px 18px;border:1px solid #d7e3ea;border-radius:7px;background:#f8fbfc}.industry-card h4{margin:0 0 5px;color:#164b6b}.industry-card .industry-intro{color:#6d808c;margin-bottom:14px}.industry-grid{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:12px}.industry-field label{font-weight:600}.industry-field input,.industry-field select,.industry-field textarea{width:100%;box-sizing:border-box}.industry-table{width:100%;margin-top:10px}.industry-table th{text-align:left;color:#617783;font-size:12px}.industry-table input{width:100%;box-sizing:border-box}.industry-table .small-number{min-width:80px}.industry-add{margin-top:9px}.industry-remove{white-space:nowrap}.profile-fields{display:none}.profile-fields.visible{display:block}@media(max-width:800px){.industry-grid{grid-template-columns:1fr}.industry-table{display:block;overflow-x:auto}}
</style>
<section class="industry-card">
    <h4>Product type &amp; optional business details</h4>
    <p class="industry-intro">Choose the closest product type. This reveals only relevant fields; category attributes still control storefront filters.</p>
    <div class="industry-grid">
        <div class="industry-field"><label for="industry_profile">Product type</label><select id="industry_profile" name="industry_profile" required><option value="general" {{ $profile==='general'?'selected':'' }}>General merchandise</option><option value="technology" {{ $profile==='technology'?'selected':'' }}>Technology / electronics</option><option value="clothing" {{ $profile==='clothing'?'selected':'' }}>Clothing / fashion</option><option value="food" {{ $profile==='food'?'selected':'' }}>Food / grocery</option><option value="medicine" {{ $profile==='medicine'?'selected':'' }}>Medicine / healthcare</option></select></div>
        <div class="industry-field profile-fields" data-profiles="food medicine"><label for="storage_instructions">Storage instructions</label><input id="storage_instructions" name="storage_instructions" value="{{ old('storage_instructions',$editingProduct->storage_instructions ?? '') }}" placeholder="Example: Store below 25°C in a dry place"></div>
    </div>
    <div class="profile-fields" data-profiles="food"><div class="industry-field"><label for="allergen_information">Ingredients / allergen information</label><textarea id="allergen_information" name="allergen_information" rows="3" placeholder="Example: Contains milk and nuts">{{ old('allergen_information',$editingProduct->allergen_information ?? '') }}</textarea></div></div>
    <div class="profile-fields" data-profiles="medicine">
        <div class="industry-grid"><div class="industry-field"><label>Generic name</label><input name="generic_name" value="{{ old('generic_name',$editingProduct->generic_name ?? '') }}"></div><div class="industry-field"><label>Strength</label><input name="strength" value="{{ old('strength',$editingProduct->strength ?? '') }}" placeholder="Example: 500 mg"></div><div class="industry-field"><label>Dosage form</label><input name="dosage_form" value="{{ old('dosage_form',$editingProduct->dosage_form ?? '') }}" placeholder="Tablet, capsule, syrup..."></div><div class="industry-field"><label class="checkbox"><input type="checkbox" name="prescription_required" value="1" {{ old('prescription_required',$editingProduct->prescription_required ?? false)?'checked':'' }}> Prescription required</label></div></div>
        <p class="help-block">These fields support catalog and stock traceability. They do not by themselves establish regulatory compliance.</p>
    </div>
</section>

<section class="industry-card" id="variant-card">
    <h4>Variants (optional)</h4><p class="industry-intro">Use for size, color, pack size, capacity, or any sellable choice with its own SKU and stock.</p>
    <table class="industry-table"><thead><tr><th>Variant name</th><th>SKU</th><th>Barcode</th><th>Price +/-</th><th>Stock</th><th>Active</th><th></th></tr></thead><tbody id="variant-rows">
    @foreach($variantRows as $index=>$row)<tr><td><input name="variants[{{ $index }}][name]" value="{{ $row['name'] ?? '' }}" placeholder="Blue / XL / 1 kg"></td><td><input name="variants[{{ $index }}][sku]" value="{{ $row['sku'] ?? '' }}"></td><td><input name="variants[{{ $index }}][barcode]" value="{{ $row['barcode'] ?? '' }}"></td><td><input type="number" step="0.01" name="variants[{{ $index }}][price_adjustment]" value="{{ $row['price_adjustment'] ?? 0 }}"></td><td><input class="small-number" type="number" min="0" name="variants[{{ $index }}][stock_quantity]" value="{{ $row['stock_quantity'] ?? 0 }}"></td><td><input type="checkbox" name="variants[{{ $index }}][is_active]" value="1" {{ ($row['is_active'] ?? true)?'checked':'' }}></td><td><button type="button" class="btn btn-small industry-remove">Remove</button></td></tr>@endforeach
    </tbody></table><button type="button" class="btn btn-small industry-add" data-add-row="variant"><i class="icon-plus"></i> Add variant</button>
</section>

<section class="industry-card profile-fields" id="lot-card" data-profiles="food medicine">
    <h4>Batch / lot traceability (optional)</h4><p class="industry-intro">Track expiry-sensitive inventory by lot. Quantities here are traceability records; the main stock quantity remains the current sellable total.</p>
    <table class="industry-table"><thead><tr><th>Lot number</th><th>Manufactured</th><th>Expires</th><th>Quantity</th><th>Supplier reference</th><th></th></tr></thead><tbody id="lot-rows">
    @foreach($lotRows as $index=>$row)<tr><td><input name="lots[{{ $index }}][lot_number]" value="{{ $row['lot_number'] ?? '' }}"></td><td><input type="date" name="lots[{{ $index }}][manufactured_at]" value="{{ $row['manufactured_at'] ?? '' }}"></td><td><input type="date" name="lots[{{ $index }}][expires_at]" value="{{ $row['expires_at'] ?? '' }}"></td><td><input type="number" min="0" name="lots[{{ $index }}][quantity]" value="{{ $row['quantity'] ?? 0 }}"></td><td><input name="lots[{{ $index }}][supplier_reference]" value="{{ $row['supplier_reference'] ?? '' }}"></td><td><button type="button" class="btn btn-small industry-remove">Remove</button></td></tr>@endforeach
    </tbody></table><button type="button" class="btn btn-small industry-add" data-add-row="lot"><i class="icon-plus"></i> Add lot</button>
</section>

<script>
document.addEventListener('DOMContentLoaded',function(){var profile=document.getElementById('industry_profile'),variantIndex={{ count($variantRows) }},lotIndex={{ count($lotRows) }};function refresh(){document.querySelectorAll('.profile-fields').forEach(function(el){el.classList.toggle('visible',(el.getAttribute('data-profiles')||'').split(' ').indexOf(profile.value)!==-1);});}function row(type,index){if(type==='variant')return '<tr><td><input name="variants['+index+'][name]" placeholder="Blue / XL / 1 kg"></td><td><input name="variants['+index+'][sku]"></td><td><input name="variants['+index+'][barcode]"></td><td><input type="number" step="0.01" name="variants['+index+'][price_adjustment]" value="0"></td><td><input type="number" min="0" name="variants['+index+'][stock_quantity]" value="0"></td><td><input type="checkbox" name="variants['+index+'][is_active]" value="1" checked></td><td><button type="button" class="btn btn-small industry-remove">Remove</button></td></tr>';return '<tr><td><input name="lots['+index+'][lot_number]"></td><td><input type="date" name="lots['+index+'][manufactured_at]"></td><td><input type="date" name="lots['+index+'][expires_at]"></td><td><input type="number" min="0" name="lots['+index+'][quantity]" value="0"></td><td><input name="lots['+index+'][supplier_reference]"></td><td><button type="button" class="btn btn-small industry-remove">Remove</button></td></tr>';}document.querySelectorAll('[data-add-row]').forEach(function(button){button.addEventListener('click',function(){var type=button.getAttribute('data-add-row'),body=document.getElementById(type+'-rows'),index=type==='variant'?variantIndex++:lotIndex++;body.insertAdjacentHTML('beforeend',row(type,index));});});document.addEventListener('click',function(event){if(event.target.classList.contains('industry-remove'))event.target.closest('tr').remove();});profile.addEventListener('change',refresh);refresh();});
</script>
